-- ============================================================
-- GENEALOGY PERSON: Eutíquio
-- Generated: 2025-12-22
-- ============================================================
-- BIRTH YEAR ESTIMATION (1900, decade):
-- Gato Preto was born 1930 and started learning from his father at age 8 (1938).
-- Assuming Eutíquio was between 25-40 years old when teaching an 8-year-old,
-- this places his birth between 1898-1913. Given that he died in 1954 and was
-- described as "a good capoeira master" (implying mature practitioner), and that
-- his own father/grandfather was African (Oleriano de Góes), a birth year around
-- 1900 (±10 years) is reasonable. Using decade precision.
-- ============================================================

INSERT INTO genealogy.person_profiles (
  name, apelido, title, portrait, public_links,
  style, style_notes_en, style_notes_pt,
  birth_year, birth_year_precision, birth_place,
  death_year, death_year_precision, death_place,
  bio_en, bio_pt, achievements_en, achievements_pt,
  notes_en, notes_pt
) VALUES (
  'Eutíquio Lúcio Góes', 'Eutíquio', NULL, NULL,
  ARRAY['https://velhosmestres.com/br/gatopreto', 'https://velhosmestres.com/en/gatopreto']::text[],
  'angola'::genealogy.style,
  NULL,
  NULL,
  1900, 'decade'::genealogy.date_precision, 'Santo Amaro da Purificação, Bahia, Brazil',
  1954, 'year'::genealogy.date_precision, NULL,
  E'Eutíquio Lúcio Góes, known as Seu Eutíquio, was a capoeirista from Santo Amaro da Purificação in the Recôncavo Baiano—the heartland of traditional Bahian capoeira. He represented a direct link to Africa: he learned capoeira from his own father, the African Oleriano de Góes, making him part of the first Brazilian-born generation in a family lineage that traced directly back to the continent.\n\nSeu Eutíquio was the father and first teacher of Mestre Gato Preto (José Gabriel Góes), one of the most celebrated Angola mestres of the 20th century. Beginning in 1938, when young José Gabriel was just eight years old, Eutíquio initiated rigorous training in a small enclosed room of their home on Rua do Pilar. His teaching method was intense: he would attack the boy with a maculelê stick or machete, forcing him to learn defense through necessity. When José Gabriel made mistakes, his father would strike his wrists to correct him.\n\nThis brutal but effective pedagogy continued for approximately four years. Around 1942, when José Gabriel was about twelve, the training came to an abrupt end. During a session, the young student landed such a powerful cabeçada (headbutt) that his father fell to the ground. Upon rising, Eutíquio chased his son while threatening him: "Come here, boy!" After this incident, he stopped teaching his son—perhaps recognizing that the student had surpassed a threshold, or perhaps wounded in his pride. The boy''s uncle João Catarino, himself a student of the legendary Besouro Mangangá, continued his education afterward.\n\nMestre Waldemar da Paixão, speaking in 1987, remembered Seu Eutíquio: "His father was called Seu Eutíquio, he''s deceased, he was a good capoeira master". The description as "a good capoeira master" from a mestre of Waldemar''s stature speaks to Eutíquio''s standing in the Santo Amaro capoeira community.\n\nEutíquio died in 1954. His legacy lives on through his son Gato Preto, who would go on to represent Brazil at the I Festival Mundial das Artes Negras in Dakar (1966), win the Berimbau de Ouro (1970), and pass the tradition to his own sons Gato II and Mestre Zeca. Through this unbroken line—from the African Oleriano de Góes to Eutíquio to Gato Preto to his grandchildren—the family represents one of the most documented multi-generational capoeira lineages.',
  E'Eutíquio Lúcio Góes, conhecido como Seu Eutíquio, era um capoeirista de Santo Amaro da Purificação no Recôncavo Baiano—o coração da capoeira tradicional baiana. Ele representava uma ligação direta com a África: aprendeu capoeira com seu próprio pai, o africano Oleriano de Góes, tornando-se parte da primeira geração nascida no Brasil em uma linhagem familiar que traçava diretamente ao continente.\n\nSeu Eutíquio foi o pai e primeiro mestre de Mestre Gato Preto (José Gabriel Góes), um dos mais celebrados mestres de Angola do século XX. A partir de 1938, quando o jovem José Gabriel tinha apenas oito anos, Eutíquio iniciou um treinamento rigoroso em um pequeno quarto fechado da casa deles na Rua do Pilar. Seu método de ensino era intenso: ele atacava o menino com um bastão de maculelê ou facão, forçando-o a aprender defesa pela necessidade. Quando José Gabriel errava, seu pai batia em seus pulsos para corrigi-lo.\n\nEssa pedagogia brutal mas eficaz continuou por aproximadamente quatro anos. Por volta de 1942, quando José Gabriel tinha cerca de doze anos, o treinamento chegou a um fim abrupto. Durante uma sessão, o jovem aluno deu uma cabeçada tão forte que seu pai caiu no chão. Ao se levantar, Eutíquio perseguiu seu filho enquanto o ameaçava: "Vem cá, menino!" Após esse incidente, ele parou de ensinar seu filho—talvez reconhecendo que o aluno havia ultrapassado um limiar, ou talvez ferido em seu orgulho. O tio do menino, João Catarino, que era aluno do lendário Besouro Mangangá, continuou sua educação depois.\n\nMestre Waldemar da Paixão, falando em 1987, lembrou de Seu Eutíquio: "O pai dele chamava Seu Eutíquio, é morto, era um bom mestre de capoeira". A descrição como "um bom mestre de capoeira" por um mestre do calibre de Waldemar fala da reputação de Eutíquio na comunidade de capoeira de Santo Amaro.\n\nEutíquio morreu em 1954. Seu legado vive através de seu filho Gato Preto, que viria a representar o Brasil no I Festival Mundial das Artes Negras em Dacar (1966), ganhar o Berimbau de Ouro (1970), e passar a tradição para seus próprios filhos Gato II e Mestre Zeca. Através dessa linha ininterrupta—do africano Oleriano de Góes a Eutíquio, a Gato Preto e seus netos—a família representa uma das linhagens de capoeira multigeracionais mais documentadas.',
  NULL,
  NULL,
  E'BIRTH YEAR ESTIMATION (1900, decade):\nGato Preto was born 1930 and started learning from his father at age 8 (1938). Assuming Eutíquio was between 25-40 years old when teaching an 8-year-old, this places his birth between 1898-1913. Using 1900 with decade precision.\n\nNAME DISCREPANCY:\n- "Eutíquio Lúcio Góes" - velhosmestres.com, capoeira.online, lalaue.com (MAJORITY)\n- "Eutíquio Lúcio Chagas" - some sources (nossa-tribo.com, lalaue.com alternate)\nUsed "Góes" as primary since his son is "José Gabriel Góes" and the family surname is consistently Góes.\n\nTEACHERS:\n- Oleriano de Góes (grandfather, African; taught him capoeira; mentioned in USP Núcleo de Artes Afro-Brasileiras article)\n\nSTUDENTS:\n- Mestre Gato Preto (José Gabriel Góes, son; began 1938 age 8, ended ~1942 after cabeçada incident)\n\nTRAINING METHOD:\n- Trained in small enclosed room at family home on Rua do Pilar, Santo Amaro\n- Used maculelê stick or machete to force defensive learning\n- Would strike wrists to correct errors\n- Training ended when son delivered powerful cabeçada that knocked him down\n\nFAMILY:\n- Father/Grandfather: Oleriano de Góes (African, capoeirista)\n- Son: José Gabriel Góes (Mestre Gato Preto)\n- Brother: João Catarino (student of Besouro Mangangá)\n- Grandson: Sinésio Souza Góes (Mestre Gato II)\n- Grandson: José Souza Góes (Mestre Zeca/Gato III)\n\nQUOTE ABOUT EUTÍQUIO:\n- Mestre Waldemar (1987): "O pai dele chamava Seu Eutíquio, é morto, era um bom mestre de capoeira".',
  E'ESTIMATIVA DO ANO DE NASCIMENTO (1900, década):\nGato Preto nasceu em 1930 e começou a aprender com seu pai aos 8 anos (1938). Assumindo que Eutíquio tinha entre 25-40 anos quando ensinava uma criança de 8 anos, isso coloca seu nascimento entre 1898-1913. Usando 1900 com precisão de década.\n\nDISCREPÂNCIA DE NOME:\n- "Eutíquio Lúcio Góes" - velhosmestres.com, capoeira.online, lalaue.com (MAIORIA)\n- "Eutíquio Lúcio Chagas" - algumas fontes (nossa-tribo.com, lalaue.com alternativo)\nUsado "Góes" como principal já que seu filho é "José Gabriel Góes" e o sobrenome da família é consistentemente Góes.\n\nMESTRES:\n- Oleriano de Góes (avô, africano; ensinou-lhe capoeira; mencionado no artigo do Núcleo de Artes Afro-Brasileiras da USP)\n\nALUNOS:\n- Mestre Gato Preto (José Gabriel Góes, filho; começou 1938 aos 8 anos, terminou ~1942 após incidente da cabeçada)\n\nMÉTODO DE TREINAMENTO:\n- Treinava em pequeno quarto fechado na casa da família na Rua do Pilar, Santo Amaro\n- Usava bastão de maculelê ou facão para forçar aprendizado defensivo\n- Batia nos pulsos para corrigir erros\n- Treinamento terminou quando filho deu cabeçada poderosa que o derrubou\n\nFAMÍLIA:\n- Pai/Avô: Oleriano de Góes (africano, capoeirista)\n- Filho: José Gabriel Góes (Mestre Gato Preto)\n- Irmão: João Catarino (aluno de Besouro Mangangá)\n- Neto: Sinésio Souza Góes (Mestre Gato II)\n- Neto: José Souza Góes (Mestre Zeca/Gato III)\n\nCITAÇÃO SOBRE EUTÍQUIO:\n- Mestre Waldemar (1987): "O pai dele chamava Seu Eutíquio, é morto, era um bom mestre de capoeira".'
)
ON CONFLICT (apelido, COALESCE(apelido_context, '')) WHERE apelido IS NOT NULL DO UPDATE SET
  name = EXCLUDED.name, title = EXCLUDED.title, portrait = EXCLUDED.portrait,
  public_links = EXCLUDED.public_links, style = EXCLUDED.style,
  style_notes_en = EXCLUDED.style_notes_en, style_notes_pt = EXCLUDED.style_notes_pt,
  birth_year = EXCLUDED.birth_year, birth_year_precision = EXCLUDED.birth_year_precision,
  birth_place = EXCLUDED.birth_place, death_year = EXCLUDED.death_year,
  death_year_precision = EXCLUDED.death_year_precision, death_place = EXCLUDED.death_place,
  bio_en = EXCLUDED.bio_en, bio_pt = EXCLUDED.bio_pt,
  achievements_en = EXCLUDED.achievements_en, achievements_pt = EXCLUDED.achievements_pt,
  notes_en = EXCLUDED.notes_en, notes_pt = EXCLUDED.notes_pt, updated_at = NOW();
