-- ============================================================
-- GENEALOGY PERSON: Gato II
-- Generated: 2026-01-10
-- Primary Source: https://velhosmestres.com/br/gatopreto
-- ============================================================
-- DEPENDENCIES: gato-preto.sql (father/teacher)
-- ============================================================
--
-- BIRTH DATE VERIFICATION:
-- Born September 7, 1950 (confirmed by velhosmestres.com main Gato Preto profile)
-- Some sources state "September 1951" but the 1969 Brasília performance (March 26)
-- mentions him as "eight years old" which would place birth in late 1960/early 1961.
-- However, velhosmestres.com explicitly states Sept 7, 1950 on the Gato Preto page.
-- Using 1950 with 'exact' precision (day-month-year confirmed).
--
-- APELIDO VARIATIONS:
-- - "Gato II" - most common, used in family/capoeira context
-- - "Mestre Góes" - used professionally at USP/ASSEBA
-- - "Mestre Gato Góes" - used in Viva Meu Mestre 2011 award
--
-- ============================================================

INSERT INTO genealogy.person_profiles (
  name, apelido, title, portrait, public_links,
  style, style_notes_en, style_notes_pt,
  birth_year, birth_year_precision, birth_place,
  death_year, death_year_precision, death_place,
  bio_en, bio_pt, achievements_en, achievements_pt,
  notes_en, notes_pt
) VALUES (
  'Sinésio Souza Góes',
  'Gato II',
  'mestre'::genealogy.title,
  NULL,
  ARRAY['https://velhosmestres.com/br/gato-1969-2', 'https://velhosmestres.com/en/gato-1970-1', 'https://sites.usp.br/nucleoartesafrobrasileiras/cursos-complementares/']::text[],
  'angola'::genealogy.style,
  E'Gato II inherited the pure Angola style of his father Mestre Gato Preto, training from childhood in the "legitimate Angola" tradition that Gato Preto learned from Cobrinha Verde, Pastinha, and Waldemar. As a musician, dancer, and composer, he brings the complete cultural package of Bahian capoeira - the musical, movement, and philosophical dimensions. His expertise extends particularly to the musical foundations: berimbau rhythms and construction, pandeiro, agogô, and capoeira singing traditions. He crafts berimbaus using materials from the Recôncavo Baiano, continuing the instrument-making tradition his father was renowned for.',
  E'Gato II herdou o estilo Angola puro de seu pai Mestre Gato Preto, treinando desde a infância na tradição da "Angola legítima" que Gato Preto aprendeu com Cobrinha Verde, Pastinha e Waldemar. Como músico, dançarino e compositor, ele traz o pacote cultural completo da capoeira baiana - as dimensões musicais, de movimento e filosóficas. Sua especialidade se estende particularmente aos fundamentos musicais: ritmos e construção de berimbau, pandeiro, agogô e tradições de canto da capoeira. Ele confecciona berimbaus usando materiais do Recôncavo Baiano, continuando a tradição de fabricação de instrumentos pela qual seu pai era renomado.',
  1950,
  'exact'::genealogy.date_precision,
  'Salvador, Bahia, Brazil',
  NULL,
  NULL,
  NULL,
  E'Sinésio Souza Góes, known as Gato II or Mestre Góes, was born on September 7, 1950, in Salvador, Bahia. He is the eldest son of Mestre Gato Preto, "O Berimbau de Ouro da Bahia," and the elder brother of Mestre Zeca (Gatinho/Gato III). His apelido "Gato II" marks him as the second generation of the Gato capoeira dynasty, a lineage his father traced back through his own father Eutíquio and grandfather, the African Oleriano de Góes.\n\nGato Preto began teaching his son capoeira in 1958 when Sinésio was eight years old, passing on the "legitimate Angola" that he himself had learned from the masters of Salvador - Cobrinha Verde, Pastinha, and Waldemar da Paixão. As his father declared to the press: "Gato II, my son and successor, will see to it that capoeira never leaves from the family."\n\nOn March 26, 1969, at age eighteen, Gato II performed at Teatro Martins Penna in Brasília alongside his father and younger brother Gatinho (Zeca). The family ensemble, consisting of seven members including Almir Barros ("Tião do Pandeiro"), presented a program of samba de roda, pandeiro demonstration, maculelê, and capoeira. This marked the final performance of their Brasília visit, after which the University of Brasília proposed contracting Mestre Gato Preto to teach.\n\nDuring the 1970s, Gato II toured extensively with the Brasil Tropical dance company across Europe. Founded in 1973 by Camisa Roxa and Domingos Campos, Brasil Tropical was one of the first groups to bring capoeira and Afro-Brazilian culture to the European continent, performing thousands of shows for audiences across the old world.\n\nReturning to Brazil, Gato II devoted himself to preserving and transmitting Bahian cultural traditions. He became the administrative coordinator of ASSEBA - the Associação de Sambadores e Sambadeiras do Estado da Bahia (Association of Samba Practitioners of Bahia State) - working to preserve samba de roda and related traditions.\n\nIn 2011, he was recognized nationally when he received the Prêmio Viva Meu Mestre (awarded by IPHAN as part of the Pró-Capoeira program), which honors mestres age 55 and over who have made fundamental contributions to the transmission and continuity of capoeira in Brazil. The prize listed him as "Sinésio Souza Góes (Mestre Gato Góes)" among the 78 mestres recognized that year.\n\nToday, Gato II teaches at the Núcleo de Artes Afro-Brasileiras da USP (University of São Paulo), leading courses on "Musicalização da Capoeira" - the musicalization of capoeira covering rhythms, chants, fundamentals, and percussion. His curriculum encompasses berimbau techniques and construction (using materials he sources from the Recôncavo Baiano), pandeiro and agogô instruction, and the singing traditions essential to the roda. He carries forward his father''s multi-dimensional mastery - as capoeirista, musician, dancer, and composer - ensuring that the cultural heritage of his family continues into future generations.',
  E'Sinésio Souza Góes, conhecido como Gato II ou Mestre Góes, nasceu em 7 de setembro de 1950, em Salvador, Bahia. É o filho mais velho de Mestre Gato Preto, "O Berimbau de Ouro da Bahia," e irmão mais velho de Mestre Zeca (Gatinho/Gato III). Seu apelido "Gato II" marca-o como a segunda geração da dinastia capoeirística dos Gato, uma linhagem que seu pai traçava através de seu próprio pai Eutíquio e avô, o africano Oleriano de Góes.\n\nGato Preto começou a ensinar capoeira ao filho em 1958, quando Sinésio tinha oito anos, transmitindo a "Angola legítima" que ele mesmo havia aprendido dos mestres de Salvador - Cobrinha Verde, Pastinha e Waldemar da Paixão. Como seu pai declarou à imprensa: "Gato II, meu filho e sucessor, cuidará para que a capoeira nunca saia da família."\n\nEm 26 de março de 1969, aos dezoito anos, Gato II se apresentou no Teatro Martins Penna em Brasília ao lado de seu pai e irmão mais novo Gatinho (Zeca). O conjunto familiar, composto por sete membros incluindo Almir Barros ("Tião do Pandeiro"), apresentou um programa de samba de roda, demonstração de pandeiro, maculelê e capoeira. Esta foi a apresentação final da visita a Brasília, após a qual a Universidade de Brasília propôs contratar Mestre Gato Preto para ensinar.\n\nDurante os anos 1970, Gato II excursionou extensivamente com a companhia de dança Brasil Tropical pela Europa. Fundada em 1973 por Camisa Roxa e Domingos Campos, a Brasil Tropical foi um dos primeiros grupos a levar a capoeira e a cultura afro-brasileira ao continente europeu, realizando milhares de apresentações para públicos do velho mundo.\n\nRetornando ao Brasil, Gato II dedicou-se a preservar e transmitir as tradições culturais baianas. Tornou-se coordenador administrativo da ASSEBA - Associação de Sambadores e Sambadeiras do Estado da Bahia - trabalhando para preservar o samba de roda e tradições relacionadas.\n\nEm 2011, foi reconhecido nacionalmente ao receber o Prêmio Viva Meu Mestre (concedido pelo IPHAN como parte do programa Pró-Capoeira), que honra mestres com 55 anos ou mais que fizeram contribuições fundamentais para a transmissão e continuidade da capoeira no Brasil. O prêmio o listou como "Sinésio Souza Góes (Mestre Gato Góes)" entre os 78 mestres reconhecidos naquele ano.\n\nHoje, Gato II ensina no Núcleo de Artes Afro-Brasileiras da USP (Universidade de São Paulo), liderando cursos sobre "Musicalização da Capoeira" - cobrindo ritmos, cantos, fundamentos e percussão. Seu currículo abrange técnicas e construção de berimbau (usando materiais que ele obtém do Recôncavo Baiano), instrução de pandeiro e agogô, e as tradições de canto essenciais à roda. Ele leva adiante a maestria multidimensional de seu pai - como capoeirista, músico, dançarino e compositor - garantindo que o patrimônio cultural de sua família continue para as gerações futuras.',
  E'Prêmio Viva Meu Mestre (IPHAN/Pró-Capoeira, 2011)\nPerformed at Teatro Martins Penna, Brasília with father and brother (1969)\nToured Europe with Brasil Tropical dance company (1970s)\nAdministrative Coordinator of ASSEBA (Associação de Sambadores e Sambadeiras do Estado da Bahia)\nTeaches at Núcleo de Artes Afro-Brasileiras da USP\nDesignated successor of Mestre Gato Preto''s capoeira lineage',
  E'Prêmio Viva Meu Mestre (IPHAN/Pró-Capoeira, 2011)\nApresentou-se no Teatro Martins Penna, Brasília com pai e irmão (1969)\nExcursionou pela Europa com a companhia de dança Brasil Tropical (anos 1970)\nCoordenador Administrativo da ASSEBA (Associação de Sambadores e Sambadeiras do Estado da Bahia)\nEnsina no Núcleo de Artes Afro-Brasileiras da USP\nSucessor designado da linhagem capoeirística de Mestre Gato Preto',
  E'BIRTH DATE: September 7, 1950 (velhosmestres.com Gato Preto profile).\nNote: Some sources state "September 1951" which appears to be an error.\n\nAPELIDO VARIATIONS:\n- "Gato II" - family/capoeira context, second generation of Gato lineage\n- "Mestre Góes" - professional context (USP, ASSEBA)\n- "Mestre Gato Góes" - used in Viva Meu Mestre 2011 award listing\n\nTEACHERS:\n- Mestre Gato Preto (father, began 1958)\n- Exposure to Cobrinha Verde, Pastinha through father''s academies\n\nFAMILY:\n- Father: Mestre Gato Preto (José Gabriel Góes, 1930-2002)\n- Younger brother: Mestre Zeca (José Souza Góes, 1956-2024)\n- Grandfather: Eutíquio Lúcio Góes (capoeirista)\n- Great-grandfather: Oleriano de Góes (African-born)\n\nMEDIA APPEARANCES:\n- 1969: Teatro Martins Penna, Brasília (performance with father and brother)\n- 1970s: Brasil Tropical European tours\n\nPROFESSIONAL ROLES:\n- Administrative Coordinator, ASSEBA\n- Instructor, Núcleo de Artes Afro-Brasileiras da USP (São Paulo)\n- Course: "Musicalização da Capoeira, toques e cânticos, fundamentos e percussão"\n\nINSTRUMENT MAKING:\n- Crafts berimbaus using materials from Recôncavo Baiano\n- Continues his father''s renowned tradition of berimbau construction',
  E'DATA DE NASCIMENTO: 7 de setembro de 1950 (perfil de Gato Preto no velhosmestres.com).\nNota: Algumas fontes indicam "setembro de 1951" que parece ser um erro.\n\nVARIAÇÕES DE APELIDO:\n- "Gato II" - contexto familiar/capoeira, segunda geração da linhagem Gato\n- "Mestre Góes" - contexto profissional (USP, ASSEBA)\n- "Mestre Gato Góes" - usado na premiação Viva Meu Mestre 2011\n\nMESTRES:\n- Mestre Gato Preto (pai, começou 1958)\n- Exposição a Cobrinha Verde, Pastinha através das academias do pai\n\nFAMÍLIA:\n- Pai: Mestre Gato Preto (José Gabriel Góes, 1930-2002)\n- Irmão mais novo: Mestre Zeca (José Souza Góes, 1956-2024)\n- Avô: Eutíquio Lúcio Góes (capoeirista)\n- Bisavô: Oleriano de Góes (nascido na África)\n\nAPARIÇÕES EM MÍDIA:\n- 1969: Teatro Martins Penna, Brasília (apresentação com pai e irmão)\n- Anos 1970: Turnês europeias da Brasil Tropical\n\nFUNÇÕES PROFISSIONAIS:\n- Coordenador Administrativo, ASSEBA\n- Instrutor, Núcleo de Artes Afro-Brasileiras da USP (São Paulo)\n- Curso: "Musicalização da Capoeira, toques e cânticos, fundamentos e percussão"\n\nFABRICAÇÃO DE INSTRUMENTOS:\n- Confecciona berimbaus usando materiais do Recôncavo Baiano\n- Continua a renomada tradição de construção de berimbaus de seu pai'
)
ON CONFLICT (apelido, COALESCE(apelido_context, '')) WHERE apelido IS NOT NULL DO UPDATE SET
  name = EXCLUDED.name, title = EXCLUDED.title, portrait = EXCLUDED.portrait,
  public_links = EXCLUDED.public_links, style = EXCLUDED.style,
  style_notes_en = EXCLUDED.style_notes_en, style_notes_pt = EXCLUDED.style_notes_pt,
  birth_year = EXCLUDED.birth_year, birth_year_precision = EXCLUDED.birth_year_precision,
  birth_place = EXCLUDED.birth_place, death_year = EXCLUDED.death_year,
  death_year_precision = EXCLUDED.death_year_precision, death_place = EXCLUDED.death_place,
  bio_en = EXCLUDED.bio_en, bio_pt = EXCLUDED.bio_pt,
  achievements_en = EXCLUDED.achievements_en, achievements_pt = EXCLUDED.achievements_pt,
  notes_en = EXCLUDED.notes_en, notes_pt = EXCLUDED.notes_pt, updated_at = NOW();
