-- ============================================================
-- GENEALOGY PERSON: Júlia Fogareira
-- Generated: 2025-12-18
-- ============================================================
-- BIRTH YEAR ESTIMATION (~1875-1890, decade precision):
-- Pastinha testified in 1969 that between 1902-1911, famous women
-- capoeiristas including Júlia Fogareira were practicing. If she
-- was an adult practitioner (20-35) during that period, she would
-- have been born approximately 1867-1891. Using midpoint ~1880
-- with decade precision. Listed alongside fighters like Besouro
-- (1895-1924) and Bigode de Seda, suggesting same generation.
-- ============================================================

INSERT INTO genealogy.person_profiles (
  name, apelido, title, portrait, public_links,
  style, style_notes_en, style_notes_pt,
  birth_year, birth_year_precision, birth_place,
  death_year, death_year_precision, death_place,
  bio_en, bio_pt, achievements_en, achievements_pt,
  notes_en, notes_pt
) VALUES (
  NULL, 'Júlia Fogareira', NULL, NULL,
  ARRAY['https://velhosmestres.com/en/pastinha-1969-3', 'https://velhosmestres.com/br/pastinha-1976']::text[],
  'angola'::genealogy.style, NULL, NULL,
  1880, 'decade'::genealogy.date_precision, 'Salvador, Bahia, Brazil',
  NULL, NULL, NULL,
  E'Júlia Fogareira was one of the rare documented female capoeiristas of early twentieth-century Bahia. Between 1902 and 1911, Salvador witnessed what Mestre Pastinha described as "a never-seen spectacle" of female capoeira mestras who were "as agile and able as the men". Pastinha listed Júlia among the famous women practitioners of this era, alongside Maria Homem, Palmeirona, and Maria Pernambucana.\n\nThese women learned capoeira not from a single source but from multiple masters available during that period, including a young Pastinha himself. The era was reportedly "a tough time for the Don Juans and for the police", suggesting these women were formidable fighters who commanded respect in Salvador''s streets.\n\nWhen asked about how women of that era practiced in their restrictive clothing, Pastinha explained their practical solution: "At that time dresses reached the ground. The women tore their skirts on the sides. They connected the rear part with the front one, putting them on their waist with a string, making a sort of pants". This adaptation was, as Pastinha noted, "enough to play capoeira with any guy".\n\nIn 1976, when O Globo newspaper interviewed Pastinha about the generation of "angoleiros de briga" (fighting angoleiros) who came before him, he listed Júlia Fogareira among legendary practitioners including Bigode de Seda, Bugalho, Américo Ciência, Besouro, Tibiriçá, Amorzinho, Três Pedaços, Doze Homens, Inimigos Sem Tripa, Zé do U, Sete Mortes, Chico Me Dá, and Maria Homem. That Júlia and Maria Homem were the only two women included in this roster of renowned fighters speaks to their exceptional skill and reputation.\n\nThe apelido "Fogareira" derives from "fogo" (fire), suggesting either a fiery temperament or an intense, passionate style of play in the roda. Some sources also list her as "Júlia Fogareiro", a variant spelling. Her inclusion among the legendary pre-modern capoeiristas places her in the same category as figures who became folklore—street fighters whose names endured through oral tradition even as written records remained scarce.\n\nLike most women capoeiristas of her era, little concrete biographical information survives beyond Pastinha''s testimonies. Academic research notes that "it is still impossible to be certain of their existence and there are confusions regarding names, due to lack of written documentation". What is certain is that Pastinha consistently remembered these women among the greatest capoeiristas he had ever known, and that their presence challenges the common assumption that early capoeira was an exclusively male practice.',
  E'Júlia Fogareira foi uma das raras capoeiristas documentadas do início do século XX na Bahia. Entre 1902 e 1911, Salvador testemunhou o que Mestre Pastinha descreveu como "um espetáculo ímpar" de verdadeiras mestras de capoeira Angola, "tão ágeis e hábeis quanto os homens". Pastinha listou Júlia entre as famosas praticantes desta era, ao lado de Maria Homem, Palmeirona e Maria Pernambucana.\n\nEssas mulheres aprenderam capoeira não de uma única fonte, mas de vários mestres disponíveis durante aquele período, incluindo o próprio Pastinha ainda jovem. A época foi supostamente "dura para os Don Juans e para a polícia", sugerindo que essas mulheres eram lutadoras formidáveis que comandavam respeito nas ruas de Salvador.\n\nQuando perguntado sobre como as mulheres daquela época praticavam com suas roupas restritivas, Pastinha explicou sua solução prática: "Naquela época os vestidos arrastavam no chão. As mulheres rasgavam suas saias nos lados. Uniam a parte de trás com a frente, prendendo-as com uma prezilha na cintura, formando uma espécie de calção". Essa adaptação era, como Pastinha observou, "suficiente para jogar capoeira com qualquer homem".\n\nEm 1976, quando o jornal O Globo entrevistou Pastinha sobre a geração de "angoleiros de briga" que vieram antes dele, ele listou Júlia Fogareira entre praticantes lendários incluindo Bigode de Seda, Bugalho, Américo Ciência, Besouro, Tibiriçá, Amorzinho, Três Pedaços, Doze Homens, Inimigos Sem Tripa, Zé do U, Sete Mortes, Chico Me Dá e Maria Homem. Que Júlia e Maria Homem foram as únicas duas mulheres incluídas nesta lista de lutadores renomados fala de sua habilidade excepcional e reputação.\n\nO apelido "Fogareira" deriva de "fogo", sugerindo seja um temperamento ardente ou um estilo de jogo intenso e apaixonado na roda. Algumas fontes também a listam como "Júlia Fogareiro", uma variação de grafia. Sua inclusão entre os lendários capoeiristas pré-modernos a coloca na mesma categoria que figuras que se tornaram folclore—lutadores de rua cujos nomes perduraram através da tradição oral mesmo quando registros escritos permaneceram escassos.\n\nComo a maioria das mulheres capoeiristas de sua era, pouca informação biográfica concreta sobrevive além dos testemunhos de Pastinha. Pesquisas acadêmicas observam que "ainda é impossível ter certeza de sua existência e há confusões em relação aos nomes, devido à falta de documentação escrita". O que é certo é que Pastinha consistentemente lembrava dessas mulheres entre os maiores capoeiristas que já conheceu, e que sua presença desafia a suposição comum de que a capoeira antiga era uma prática exclusivamente masculina.',
  NULL, NULL,
  E'BIRTH YEAR ESTIMATION (1880, decade):\nPastinha testified in 1969 that between 1902-1911, famous women capoeiristas including Júlia Fogareira were practicing. If she was an adult practitioner (20-35) during peak activity, born approximately 1867-1891. Using 1880 as midpoint.\n\nNAME VARIATION:\n- "Júlia Fogareira" - velhosmestres.com, O Globo 1976 (majority)\n- "Júlia Fogareiro" - some French academic sources\n- "Fogareira" sometimes appears as standalone apelido\n\nMEDIA APPEARANCES:\n- 1967: Testimony by Mestre Pastinha (Museu da Imagem e do Som) - mentioned among legendary practitioners\n- 1969: A Tarde newspaper article (Feb 24, 1969) - listed among famous women capoeiristas 1902-1911\n- 1976: O Globo interview with Pastinha - included in list of angoleiros de briga\n\nTEACHERS:\n- Mestre Pastinha (among others) - "learned the art not only with Mestre Pastinha but also with other masters of the time"\n- Multiple unspecified masters of the 1900-1911 era\n\nCONTEMPORARIES:\n- Maria Homem (fellow female capoeirista)\n- Palmeirona (fellow female capoeirista)\n- Maria Pernambucana (fellow female capoeirista)\n- Bigode de Seda, Bugalho, Américo Ciência, Besouro, Tibiriçá, Amorzinho, Três Pedaços, Doze Homens, Inimigos Sem Tripa, Zé do U, Sete Mortes, Chico Me Dá (male contemporaries)\n\nHISTORICAL CONTEXT:\nWomen in early 20th century capoeira had to break gender boundaries to enter spaces denied to them. Some had to disguise themselves as men. The fact that Pastinha remembered these women by name, decades later, speaks to their exceptional impact.\n\nSOURCE QUALITY:\n- Primary: Mestre Pastinha interviews (1967, 1969, 1976) - high reliability\n- Secondary: Academic papers note uncertainty about exact biographical details due to oral tradition transmission\n- Documentation gap: No known photographs, arrest records, or independent contemporary mentions',
  E'ESTIMATIVA DE ANO DE NASCIMENTO (1880, década):\nPastinha testemunhou em 1969 que entre 1902-1911, famosas mulheres capoeiristas incluindo Júlia Fogareira estavam praticando. Se ela era uma praticante adulta (20-35) durante o pico de atividade, nascida aproximadamente 1867-1891. Usando 1880 como ponto médio.\n\nVARIAÇÃO DE NOME:\n- "Júlia Fogareira" - velhosmestres.com, O Globo 1976 (maioria)\n- "Júlia Fogareiro" - algumas fontes acadêmicas francesas\n- "Fogareira" às vezes aparece como apelido independente\n\nAPARIÇÕES NA MÍDIA:\n- 1967: Testemunho de Mestre Pastinha (Museu da Imagem e do Som) - mencionada entre praticantes lendários\n- 1969: Artigo do jornal A Tarde (24 fev 1969) - listada entre famosas mulheres capoeiristas 1902-1911\n- 1976: Entrevista do O Globo com Pastinha - incluída na lista de angoleiros de briga\n\nMESTRES:\n- Mestre Pastinha (entre outros) - "aprenderam a arte não só com Mestre Pastinha mas também com outros mestres da época"\n- Múltiplos mestres não especificados da era 1900-1911\n\nCONTEMPORÂNEOS:\n- Maria Homem (companheira capoeirista)\n- Palmeirona (companheira capoeirista)\n- Maria Pernambucana (companheira capoeirista)\n- Bigode de Seda, Bugalho, Américo Ciência, Besouro, Tibiriçá, Amorzinho, Três Pedaços, Doze Homens, Inimigos Sem Tripa, Zé do U, Sete Mortes, Chico Me Dá (contemporâneos masculinos)\n\nCONTEXTO HISTÓRICO:\nMulheres na capoeira do início do século XX tiveram que quebrar fronteiras de gênero para entrar em espaços que lhes eram negados. Algumas tiveram que se disfarçar de homens. O fato de Pastinha lembrar dessas mulheres pelo nome, décadas depois, fala de seu impacto excepcional.\n\nQUALIDADE DAS FONTES:\n- Primária: Entrevistas de Mestre Pastinha (1967, 1969, 1976) - alta confiabilidade\n- Secundária: Artigos acadêmicos notam incerteza sobre detalhes biográficos exatos devido à transmissão por tradição oral\n- Lacuna documental: Sem fotografias conhecidas, registros de prisão, ou menções contemporâneas independentes'
)
ON CONFLICT (apelido, COALESCE(apelido_context, '')) WHERE apelido IS NOT NULL DO UPDATE SET
  name = EXCLUDED.name, title = EXCLUDED.title, portrait = EXCLUDED.portrait,
  public_links = EXCLUDED.public_links, style = EXCLUDED.style,
  style_notes_en = EXCLUDED.style_notes_en, style_notes_pt = EXCLUDED.style_notes_pt,
  birth_year = EXCLUDED.birth_year, birth_year_precision = EXCLUDED.birth_year_precision,
  birth_place = EXCLUDED.birth_place, death_year = EXCLUDED.death_year,
  death_year_precision = EXCLUDED.death_year_precision, death_place = EXCLUDED.death_place,
  bio_en = EXCLUDED.bio_en, bio_pt = EXCLUDED.bio_pt,
  achievements_en = EXCLUDED.achievements_en, achievements_pt = EXCLUDED.achievements_pt,
  notes_en = EXCLUDED.notes_en, notes_pt = EXCLUDED.notes_pt, updated_at = NOW();
