-- ============================================================
-- GENEALOGY PERSON: King Kong
-- Generated: 2026-01-12
-- ============================================================
-- BIRTH YEAR ESTIMATION (1955, decade):
-- - Born "in the 1950s" per ikiogato.comunidades.net source
-- - Teacher Inauá (estimated birth ~1940) would have been training students by 1970s
-- - King Kong participated in Quinta da Boa Vista rodas (famous in 1950s-1970s)
-- - If he participated as an adult (20-30 years old) in the 1970s, birth ~1950-1960
-- - Student Baia founded Geração Nagô in 2013; if Baia was 30-40, born ~1973-1983
-- - King Kong training Baia in ~1990s as established mestre (age 35-45) suggests birth ~1950-1960
-- - Midpoint estimate: ~1955
-- ============================================================

INSERT INTO genealogy.person_profiles (
  name, apelido, title, portrait, public_links,
  style, style_notes_en, style_notes_pt,
  birth_year, birth_year_precision, birth_place,
  death_year, death_year_precision, death_place,
  bio_en, bio_pt, achievements_en, achievements_pt,
  notes_en, notes_pt
) VALUES (
  'Nelson Luís do Carmo', 'King Kong', 'mestre'::genealogy.title, NULL,
  ARRAY['https://ikiogato.comunidades.net/grao-mestre-king-kong-do-rio-de-janeiro', 'https://ikiogato.comunidades.net/geracao-nago2']::text[],
  'mixed'::genealogy.style,
  E'Trained in the Angola tradition through the lineage of Onça Preta via Mestre Inauá. Practiced at the legendary Quinta da Boa Vista roda, known for its intensity and exclusivity. His lineage today (through Geração Nagô) describes itself as contemporary rooted in Angola.',
  E'Treinado na tradição Angola através da linhagem de Onça Preta via Mestre Inauá. Jogou na lendária roda da Quinta da Boa Vista, conhecida por sua intensidade e exclusividade. Sua linhagem hoje (através da Geração Nagô) se descreve como contemporânea enraizada na Angola.',
  1955, 'decade'::genealogy.date_precision, 'Rio de Janeiro, Brazil',
  NULL, NULL, NULL,
  E'Nelson Luís do Carmo, known as Grão Mestre King Kong, is a pivotal figure in the transmission of Bahian capoeira angola to Rio de Janeiro. He earned his apelido "due to being large and strong" - a fitting name for a man who would become a pillar of capoeira in the city.\n\nKing Kong was a direct student of Mestre Inauá Mendes, who himself trained under Mestre Onça Preta (Cícero Navarro, 1909-2006) - one of the legendary angoleiros who survived the brutal Pedrito persecution in 1920s Salvador. This lineage connects King Kong directly to the old masters of Salvador: Samuel Querido de Deus, Pastinha, Aberrê, and others who shaped capoeira angola in Bahia.\n\nHe came from the capoeira rodas held at Quinta da Boa Vista - the famous public park in Rio de Janeiro that housed the National Museum. These rodas were described as places "where only those who knew how to play and had courage could enter" (onde só entrava quem sabia e tinha coragem). The Quinta da Boa Vista roda, along with the carnival roda at Central Station and the roda at the Nossa Senhora da Penha festivities, were among the most famous street rodas in Rio during the 1950s-1970s. It was at the Quinta da Boa Vista roda that Mestre Dentinho made history by being the first capoeirista to perform a somersault in a Rio roda in the 1960s.\n\nKing Kong founded Grupo Capoeirarte and serves as its president. Based in Engenho Novo, Rio de Janeiro, he dedicated his life to passing on the tradition he received from Inauá.\n\nHis first student to achieve the mestre title was Mestre Baia (Thiago da Silva Costa), who went on to found Associação Cultural de Capoeira Geração Nagô on November 30, 2013. The organization operates in the Jacarezinho favela of Rio de Janeiro and emphasizes "discipline, respect, friendship, cooperation and faith" (disciplina, respeito, amizade, cooperação e fé).\n\nDespite being blind in both eyes today, King Kong remains in excellent health and mental clarity. He continues to be honored by his lineage and was visited by the Associação Cultural de Capoeira Geração Nagô, who documented his trajectory through a video interview directed by Mestre Baia and conducted by Professor Empadinha.',
  E'Nelson Luís do Carmo, conhecido como Grão Mestre King Kong, é uma figura fundamental na transmissão da capoeira angola baiana para o Rio de Janeiro. Ganhou seu apelido "por ser grande e forte" - um nome apropriado para um homem que se tornaria um pilar da capoeira na cidade.\n\nKing Kong foi aluno direto de Mestre Inauá Mendes, que por sua vez treinou com Mestre Onça Preta (Cícero Navarro, 1909-2006) - um dos lendários angoleiros que sobreviveu à brutal perseguição de Pedrito nos anos 1920 em Salvador. Esta linhagem conecta King Kong diretamente aos velhos mestres de Salvador: Samuel Querido de Deus, Pastinha, Aberrê, e outros que moldaram a capoeira angola na Bahia.\n\nEle veio das rodas de capoeira realizadas na Quinta da Boa Vista - o famoso parque público no Rio de Janeiro que abrigava o Museu Nacional. Essas rodas eram descritas como lugares "onde só entrava quem sabia e tinha coragem". A roda da Quinta da Boa Vista, junto com a roda de carnaval na Estação Central e a roda nas festividades de Nossa Senhora da Penha, estavam entre as mais famosas rodas de rua do Rio durante os anos 1950-1970. Foi na roda da Quinta da Boa Vista que Mestre Dentinho fez história ao ser o primeiro capoeirista a realizar um salto mortal numa roda carioca nos anos 1960.\n\nKing Kong fundou o Grupo Capoeirarte e serve como seu presidente. Baseado no Engenho Novo, Rio de Janeiro, dedicou sua vida a transmitir a tradição que recebeu de Inauá.\n\nSeu primeiro aluno a conquistar o título de mestre foi Mestre Baia (Thiago da Silva Costa), que fundou a Associação Cultural de Capoeira Geração Nagô em 30 de novembro de 2013. A organização opera na favela do Jacarezinho no Rio de Janeiro e enfatiza "disciplina, respeito, amizade, cooperação e fé".\n\nApesar de estar cego em ambos os olhos hoje, King Kong permanece com excelente saúde e clareza mental. Continua sendo honrado por sua linhagem e foi visitado pela Associação Cultural de Capoeira Geração Nagô, que documentou sua trajetória através de uma entrevista em vídeo dirigida por Mestre Baia e conduzida pelo Professor Empadinha.',
  E'President and founder of Grupo Capoeirarte; trained Mestre Baia who founded Geração Nagô; maintained the Onça Preta → Inauá lineage in Rio de Janeiro; practiced at the legendary Quinta da Boa Vista roda.',
  E'Presidente e fundador do Grupo Capoeirarte; formou Mestre Baia que fundou a Geração Nagô; manteve a linhagem Onça Preta → Inauá no Rio de Janeiro; jogou na lendária roda da Quinta da Boa Vista.',
  E'BIRTH YEAR ESTIMATION (1955, decade):\n- Born "in the 1950s" per ikiogato.comunidades.net source\n- Teacher Inauá (estimated birth ~1940) would have been training students by 1970s\n- Participated in Quinta da Boa Vista rodas (famous in 1950s-1970s)\n- Student Baia founded Geração Nagô in 2013; timeline suggests King Kong born ~1950-1960\n- Midpoint estimate: ~1955\n\nTITLE NOTE:\nReferred to as "Grão Mestre" (Grand Master) by his lineage, but stored as "mestre" per database enum. The honorific "Grão" indicates senior status and deep respect.\n\nAPELIDO ORIGIN:\nNicknamed "King Kong" due to being "grande e forte" (large and strong).\n\nHEALTH STATUS:\nCurrently blind in both eyes, but in good health and mentally lucid.\n\nLOCATION:\nEngenho Novo, Rio de Janeiro.\n\nTEACHERS:\n- Mestre Inauá Mendes - primary teacher; learned in Rio de Janeiro\n\nSTUDENTS:\n- Mestre Baia (Thiago da Silva Costa) - first student to receive mestre title; founded Geração Nagô (2013)\n- Professor Empadinha - coordinator of Geração Nagô; created Projeto Maitá do Amanhã\n- Clarck, Saimon, Riquinho, Paquito, Kaikão - students documented in video production\n\nRODA ASSOCIATIONS:\n- Quinta da Boa Vista roda - famous street roda in Rio (1950s-1970s); described as exclusive, only for skilled and brave players\n\nMEDIA APPEARANCES:\n- Video interview documenting his capoeira trajectory; directed by Mestre Baia, interview by Professor Empadinha\n\nGROUPS:\n- Grupo Capoeirarte (founder/president)\n- Associated with Roda Viva (Mestre Bom Fim) through his lineage',
  E'ESTIMATIVA ANO DE NASCIMENTO (1955, década):\n- Nascido "nos anos 1950" segundo fonte ikiogato.comunidades.net\n- Mestre Inauá (nascimento estimado ~1940) estaria formando alunos nos anos 1970\n- Participou das rodas da Quinta da Boa Vista (famosas nos anos 1950-1970)\n- Aluno Baia fundou Geração Nagô em 2013; cronologia sugere King Kong nascido ~1950-1960\n- Estimativa média: ~1955\n\nNOTA SOBRE TÍTULO:\nReferido como "Grão Mestre" por sua linhagem, mas armazenado como "mestre" conforme enum do banco de dados. O honorífico "Grão" indica status sênior e profundo respeito.\n\nORIGEM DO APELIDO:\nApelidado "King Kong" por ser "grande e forte".\n\nSTATUS DE SAÚDE:\nAtualmente cego em ambos os olhos, mas com boa saúde e lucidez mental.\n\nLOCALIZAÇÃO:\nEngenho Novo, Rio de Janeiro.\n\nMESTRES:\n- Mestre Inauá Mendes - mestre principal; aprendeu no Rio de Janeiro\n\nALUNOS:\n- Mestre Baia (Thiago da Silva Costa) - primeiro aluno a receber título de mestre; fundou Geração Nagô (2013)\n- Professor Empadinha - coordenador da Geração Nagô; criou Projeto Maitá do Amanhã\n- Clarck, Saimon, Riquinho, Paquito, Kaikão - alunos documentados na produção de vídeo\n\nASSOCIAÇÕES DE RODA:\n- Roda da Quinta da Boa Vista - famosa roda de rua no Rio (décadas de 1950-1970); descrita como exclusiva, só para jogadores habilidosos e corajosos\n\nAPARIÇÕES NA MÍDIA:\n- Entrevista em vídeo documentando sua trajetória na capoeira; direção de Mestre Baia, entrevista por Professor Empadinha\n\nGRUPOS:\n- Grupo Capoeirarte (fundador/presidente)\n- Associado ao Roda Viva (Mestre Bom Fim) através de sua linhagem'
)
ON CONFLICT (apelido, COALESCE(apelido_context, '')) WHERE apelido IS NOT NULL DO UPDATE SET
  name = EXCLUDED.name, title = EXCLUDED.title, portrait = EXCLUDED.portrait,
  public_links = EXCLUDED.public_links, style = EXCLUDED.style,
  style_notes_en = EXCLUDED.style_notes_en, style_notes_pt = EXCLUDED.style_notes_pt,
  birth_year = EXCLUDED.birth_year, birth_year_precision = EXCLUDED.birth_year_precision,
  birth_place = EXCLUDED.birth_place, death_year = EXCLUDED.death_year,
  death_year_precision = EXCLUDED.death_year_precision, death_place = EXCLUDED.death_place,
  bio_en = EXCLUDED.bio_en, bio_pt = EXCLUDED.bio_pt,
  achievements_en = EXCLUDED.achievements_en, achievements_pt = EXCLUDED.achievements_pt,
  notes_en = EXCLUDED.notes_en, notes_pt = EXCLUDED.notes_pt, updated_at = NOW();
