-- ============================================================
-- GENEALOGY PERSON: Maria Homem
-- Generated: 2025-12-20
-- ============================================================
-- BIRTH YEAR ESTIMATION (~1875-1890, decade precision):
-- Pastinha testified in 1969 that between 1902-1911, famous women
-- capoeiristas including Maria Homem were practicing. If she was
-- an adult practitioner (20-35) during that period, she would
-- have been born approximately 1867-1891. Using midpoint ~1880
-- with decade precision. Listed alongside Júlia Fogareira and
-- fighters like Besouro (1895-1924), suggesting same generation.
-- ============================================================

INSERT INTO genealogy.person_profiles (
  name, apelido, title, portrait, public_links,
  style, style_notes_en, style_notes_pt,
  birth_year, birth_year_precision, birth_place,
  death_year, death_year_precision, death_place,
  bio_en, bio_pt, achievements_en, achievements_pt,
  notes_en, notes_pt
) VALUES (
  NULL, 'Maria Homem', NULL, NULL,
  ARRAY['https://velhosmestres.com/en/pastinha-1969-2', 'https://velhosmestres.com/br/pastinha-1976', 'https://papoeira.com/en/dona-maria-do-camboata-capoeira-song-lyrics-meaning-and-history/']::text[],
  'angola'::genealogy.style, NULL, NULL,
  1880, 'decade'::genealogy.date_precision, 'Salvador, Bahia, Brazil',
  NULL, NULL, NULL,
  E'Maria Homem was one of the most formidable female capoeiristas of early twentieth-century Bahia, whose legendary feats against police officers became part of Salvador''s oral tradition. Her apelido, "Maria the Man," speaks to the reputation she earned in a male-dominated world through sheer fighting ability.\n\nThe primary account of Maria Homem comes from Mestre Pastinha in a 1969 interview with Diário Popular. She frequented a "birosca" (small bar) at Largo do Pelourinho, where she liked to "tomar uns tragos" (have some drinks). Her reputation was such that "até o delegado tinha mêdo"—even the police delegate feared her—and "não havia polícia que a prendesse" (no police could arrest her).\n\nPastinha recounted a specific confrontation: An "outsider corporal" (cabo forasteiro) tried to prove himself by arresting the intoxicated Maria Homem. The local officers, knowing her reputation, refused to obey his order. Undeterred, the corporal attempted the arrest himself. According to Pastinha, "he flew six meters" and his companions fled. The stubborn corporal returned with reinforcements, only to suffer the same fate—witnesses across the Pelourinho slope saw "soldado avoando" (soldiers flying) down the hillside.\n\nMaria Homem was active during what Pastinha described as a golden era for women in capoeira. Between 1902 and 1911, Salvador witnessed "an exhibition of real mestras of capoeira Angola, who were as agile and able as the men." These women adapted their restrictive clothing to practice: they tore their floor-length skirts on the sides, connecting front and back with a string at the waist to create improvised pants—"enough to play capoeira with any guy," as Pastinha noted.\n\nIn his 1988 book *Capoeira Angola*, Pastinha named only two female capoeiristas when honoring the practitioners of his era: "Júlia Fogareiro e Maria Homem" (p. 18). In 1976, when O Globo interviewed him about the generation of "angoleiros de briga" (fighting angoleiros) who came before him, Maria Homem appeared alongside legendary names: Bigode de Seda, Bugalho, Américo Ciência, Besouro, Tibiriçá, Amorzinho, Três Pedaços, Doze Homens, Inimigos Sem Tripa, Zé do U, Sete Mortes, Chico Me Dá, and Júlia Fogareira. That Maria Homem was one of only two women in this roster speaks to her exceptional skill.\n\nPastinha lamented that women of Maria Homem''s caliber no longer existed: "É pena que não haja mais mulheres de tal estofo, pois a mulher deve também compartilhar da defesa de seu lar" (It''s a pity there are no more women of such material, because women should also share in defending their home).\n\nMaria Homem is sometimes confused with other legendary female capoeiristas, particularly Maria Doze Homens (Maria Twelve Men), but sources distinguish them as separate figures. Her story represents the often-forgotten history of women in early capoeira, who broke gender barriers in a male-dominated practice.',
  E'Maria Homem foi uma das mais formidáveis capoeiristas do início do século XX na Bahia, cujos feitos lendários contra policiais tornaram-se parte da tradição oral de Salvador. Seu apelido, "Maria Homem," fala da reputação que ela conquistou em um mundo dominado por homens através de pura habilidade de luta.\n\nO principal relato sobre Maria Homem vem de Mestre Pastinha em uma entrevista de 1969 ao Diário Popular. Ela frequentava uma "birosca" no Largo do Pelourinho, onde gostava de "tomar uns tragos." Sua reputação era tal que "até o delegado tinha mêdo" e "não havia polícia que a prendesse."\n\nPastinha contou um confronto específico: Um "cabo forasteiro" tentou se provar prendendo a embriagada Maria Homem. Os policiais locais, conhecendo sua reputação, recusaram obedecer à sua ordem. Sem se intimidar, o cabo tentou a prisão ele mesmo. Segundo Pastinha, "ele voou uns seis metros" e seus companheiros fugiram. O teimoso cabo voltou com reforço, apenas para sofrer o mesmo destino—testemunhas por toda a ladeira do Pelourinho viram "soldado avoando" pela encosta.\n\nMaria Homem estava ativa durante o que Pastinha descreveu como uma era dourada para mulheres na capoeira. Entre 1902 e 1911, Salvador testemunhou "uma exibição de verdadeiras mestras de capoeira Angola, tão ágeis e hábeis quanto os homens." Essas mulheres adaptaram suas roupas restritivas para praticar: rasgavam suas saias que arrastavam no chão nos lados, conectando frente e trás com uma prezilha na cintura para criar calções improvisados—"suficiente para jogar capoeira com qualquer homem," como Pastinha observou.\n\nEm seu livro de 1988 *Capoeira Angola*, Pastinha nomeou apenas duas mulheres capoeiristas ao homenagear os praticantes de sua era: "Júlia Fogareiro e Maria Homem" (p. 18). Em 1976, quando O Globo o entrevistou sobre a geração de "angoleiros de briga" que vieram antes dele, Maria Homem apareceu ao lado de nomes lendários: Bigode de Seda, Bugalho, Américo Ciência, Besouro, Tibiriçá, Amorzinho, Três Pedaços, Doze Homens, Inimigos Sem Tripa, Zé do U, Sete Mortes, Chico Me Dá e Júlia Fogareira. Que Maria Homem foi uma das únicas duas mulheres nesta lista fala de sua habilidade excepcional.\n\nPastinha lamentava que mulheres do calibre de Maria Homem não existiam mais: "É pena que não haja mais mulheres de tal estofo, pois a mulher deve também compartilhar da defesa de seu lar."\n\nMaria Homem às vezes é confundida com outras lendárias capoeiristas, particularmente Maria Doze Homens, mas as fontes as distinguem como figuras separadas. Sua história representa a frequentemente esquecida história das mulheres na capoeira antiga, que quebraram barreiras de gênero em uma prática dominada por homens.',
  NULL, NULL,
  E'BIRTH YEAR ESTIMATION (1880, decade):\nPastinha testified in 1969 that between 1902-1911, famous women capoeiristas including Maria Homem were practicing. If she was an adult practitioner (20-35) during peak activity, born approximately 1867-1891. Using 1880 as midpoint with decade precision.\n\nNAME:\nApelido "Maria Homem" translates as "Maria the Man" - indicating her reputation for masculine fighting prowess. No civil name documented.\n\nDISTINCTION FROM OTHER MARIAS:\n- Maria Homem (this profile) - DISTINCT from Maria Doze Homens\n- Maria Doze Homens (Maria Twelve Men) - different person; earned nickname for knocking out 12 men; associated with Mercado Modelo and Cais Dourado\n- Maria do Camboatá - DISTINCT; subject of famous capoeira song\n- Maria Felipa de Oliveira - DISTINCT; 19th century independence fighter\nPapoeira.com explicitly states these are different individuals.\n\nMEDIA APPEARANCES:\n- 1967: Testimony by Mestre Pastinha (Museu da Imagem e do Som) - named among legendary practitioners\n- 1969: Diário Popular newspaper article (Nov 16, 1969) - detailed story of police confrontation\n- 1976: O Globo interview with Pastinha (Apr 11, 1976) - included in list of angoleiros de briga\n- 1988: Published in Pastinha''s book "Capoeira Angola" p. 18\n\nRODA LOCATION: Largo do Pelourinho, Salvador, Bahia (frequented bar there)\n\nTEACHERS:\n- Multiple unspecified masters of the 1900-1911 era\n- Possibly Mestre Pastinha (among others) - Pastinha stated women of this era "learned the art not only with Mestre Pastinha but also with other masters of the time"\n\nCONTEMPORARIES:\n- Júlia Fogareira (fellow female capoeirista; only other woman named by Pastinha)\n- Palmeirona (fellow female capoeirista of 1902-1911 era)\n- Maria Pernambucana (fellow female capoeirista of 1902-1911 era)\n- Bigode de Seda, Bugalho, Américo Ciência, Besouro, Tibiriçá, Amorzinho, Três Pedaços, Doze Homens, Inimigos Sem Tripa, Zé do U, Sete Mortes, Chico Me Dá (male contemporaries in angoleiros de briga list)\n\nHISTORICAL CONTEXT:\nWomen in early 20th century capoeira had to break gender boundaries in a male-dominated practice. The era 1902-1911 was reportedly "a tough time for the Don Juans and for the police."\n\nSOURCE QUALITY:\n- Primary: Mestre Pastinha interviews (1967, 1969, 1976) and book (1988) - high reliability\n- Secondary: Academic papers note uncertainty about exact biographical details due to oral tradition\n- Documentation gap: No known photographs, arrest records, or independent contemporary newspaper mentions',
  E'ESTIMATIVA DE ANO DE NASCIMENTO (1880, década):\nPastinha testemunhou em 1969 que entre 1902-1911, famosas mulheres capoeiristas incluindo Maria Homem estavam praticando. Se ela era uma praticante adulta (20-35) durante o pico de atividade, nascida aproximadamente 1867-1891. Usando 1880 como ponto médio com precisão de década.\n\nNOME:\nApelido "Maria Homem" traduz-se como "Maria o Homem" - indicando sua reputação por proeza de luta masculina. Nenhum nome civil documentado.\n\nDISTINÇÃO DE OUTRAS MARIAS:\n- Maria Homem (este perfil) - DISTINTA de Maria Doze Homens\n- Maria Doze Homens - pessoa diferente; ganhou apelido por nocautear 12 homens; associada ao Mercado Modelo e Cais Dourado\n- Maria do Camboatá - DISTINTA; tema de famosa música de capoeira\n- Maria Felipa de Oliveira - DISTINTA; lutadora pela independência do século XIX\nPapoeira.com explicitamente afirma que são indivíduos diferentes.\n\nAPARIÇÕES NA MÍDIA:\n- 1967: Testemunho de Mestre Pastinha (Museu da Imagem e do Som) - nomeada entre praticantes lendários\n- 1969: Artigo do Diário Popular (16 nov 1969) - história detalhada do confronto com a polícia\n- 1976: Entrevista do O Globo com Pastinha (11 abr 1976) - incluída na lista de angoleiros de briga\n- 1988: Publicada no livro de Pastinha "Capoeira Angola" p. 18\n\nLOCAL DE RODA: Largo do Pelourinho, Salvador, Bahia (frequentava bar lá)\n\nMESTRES:\n- Múltiplos mestres não especificados da era 1900-1911\n- Possivelmente Mestre Pastinha (entre outros) - Pastinha afirmou que mulheres desta era "aprenderam a arte não só com Mestre Pastinha mas também com outros mestres da época"\n\nCONTEMPORÂNEOS:\n- Júlia Fogareira (companheira capoeirista; única outra mulher nomeada por Pastinha)\n- Palmeirona (companheira capoeirista da era 1902-1911)\n- Maria Pernambucana (companheira capoeirista da era 1902-1911)\n- Bigode de Seda, Bugalho, Américo Ciência, Besouro, Tibiriçá, Amorzinho, Três Pedaços, Doze Homens, Inimigos Sem Tripa, Zé do U, Sete Mortes, Chico Me Dá (contemporâneos masculinos na lista de angoleiros de briga)\n\nCONTEXTO HISTÓRICO:\nMulheres na capoeira do início do século XX tiveram que quebrar fronteiras de gênero em uma prática dominada por homens. A era 1902-1911 foi supostamente "dura para os Don Juans e para a polícia."\n\nQUALIDADE DAS FONTES:\n- Primária: Entrevistas de Mestre Pastinha (1967, 1969, 1976) e livro (1988) - alta confiabilidade\n- Secundária: Artigos acadêmicos notam incerteza sobre detalhes biográficos exatos devido à tradição oral\n- Lacuna documental: Sem fotografias conhecidas, registros de prisão, ou menções contemporâneas independentes'
)
ON CONFLICT (apelido, COALESCE(apelido_context, '')) WHERE apelido IS NOT NULL DO UPDATE SET
  name = EXCLUDED.name, title = EXCLUDED.title, portrait = EXCLUDED.portrait,
  public_links = EXCLUDED.public_links, style = EXCLUDED.style,
  style_notes_en = EXCLUDED.style_notes_en, style_notes_pt = EXCLUDED.style_notes_pt,
  birth_year = EXCLUDED.birth_year, birth_year_precision = EXCLUDED.birth_year_precision,
  birth_place = EXCLUDED.birth_place, death_year = EXCLUDED.death_year,
  death_year_precision = EXCLUDED.death_year_precision, death_place = EXCLUDED.death_place,
  bio_en = EXCLUDED.bio_en, bio_pt = EXCLUDED.bio_pt,
  achievements_en = EXCLUDED.achievements_en, achievements_pt = EXCLUDED.achievements_pt,
  notes_en = EXCLUDED.notes_en, notes_pt = EXCLUDED.notes_pt, updated_at = NOW();
