-- ============================================================
-- GENEALOGY PERSON: Perninha
-- Generated: 2026-01-10
-- ============================================================
-- Ecuadorian mestre; one of only three Ecuadorian mestres of capoeira.
-- Co-founded Centro do Mundo (2011); Director Ecuador.
-- Received mestre cord May 2013 from Zé Maria and Paulinho Salmon.
-- Started capoeira 1998 with Marco Ayala (Mestre Marcos).
-- Academic background in education sciences and learning difficulties.
-- ============================================================

INSERT INTO genealogy.person_profiles (
  name, apelido, title, portrait, public_links,
  style, style_notes_en, style_notes_pt,
  birth_year, birth_year_precision, birth_place,
  death_year, death_year_precision, death_place,
  bio_en, bio_pt, achievements_en, achievements_pt,
  notes_en, notes_pt
) VALUES (
  'Marco Herrera',
  'Perninha',
  'mestre'::genealogy.title,
  NULL,
  ARRAY['https://www.centrodomundo.org/biografias', 'https://www.centrodomundo.org/centro-do-mundo']::text[],
  'regional'::genealogy.style,
  E'Trained in the Zé Maria/Zema lineage, which descends from Paulinho Salmon and Euclides Paes of Rio de Janeiro. The group follows Regional traditions. Perninha combines capoeira practice with academic study of education sciences and psychomotor development, writing articles on self-understanding through capoeira.',
  E'Treinado na linhagem Zé Maria/Zema, que descende de Paulinho Salmon e Euclides Paes do Rio de Janeiro. O grupo segue tradições Regional. Perninha combina a prática da capoeira com estudo acadêmico de ciências da educação e desenvolvimento psicomotor, escrevendo artigos sobre autoconhecimento através da capoeira.',
  1980, 'decade'::genealogy.date_precision, 'Ecuador',
  NULL, NULL::genealogy.date_precision, NULL,
  E'Marco Herrera began his journey in capoeira in 1998, joining Grupo Zema de Capoeira in Ecuador under the instruction of Marco Ayala, who would later become Mestre Marcos. The following year, in 1999, he received his first cord and the apelido "Perninha"—Portuguese for "little leg"—which has accompanied him ever since.\n\nFrom 1998 onward, Perninha never stopped being connected to capoeira, whether through practice or teaching. As one of the early students of Grupo Zema after Mestre Zé Maria returned to Brazil in 1996, he was part of the foundation that Marco Ayala was building for Ecuadorian capoeira.\n\nIn December 2011, Perninha, together with his "companions and brothers" Henry Vizcarra (Carvão) and Daniel Herrera (Pandeiro), founded the Grupo Internacional de Capoeira Centro do Mundo in Quito. The founding date was December 17, 2011. The project was endorsed and promoted by Mestre Zé Maria, the pioneer of capoeira in Ecuador. Centro do Mundo emerged with the support of other capoeira professionals including Contramestres Mario Molina and Braulio Rosero (Pantera), as well as professors Jonathan Chala, Juan Misael Prado (Canguru), and Fernando Hidalgo (Fernandinho 22).\n\nIn May 2013, Perninha received the white cord (corda branca) of mestre de capoeira from the hands of Mestre Zé Maria (José Maria Da Silva) and his master Mestre Paulinho Salmon (Paulo Salmon), both from Rio de Janeiro. This ceremony marked his entry into a select group—he has the privilege and responsibility of being one of only three Ecuadorian mestres of capoeira, an honor shared with Mestre Marcos and Mestre Carvão.\n\nPerninha serves as Director Ecuador of Centro do Mundo, the first Ecuadorian capoeira group with international branches in the USA, Germany, and Spain. He has visited other capoeira schools in both Ecuador and Brazil to learn and share knowledge, and has been invited to various capoeira events to participate, give workshops, and serve as a judge.\n\nBeyond his capoeira work, Perninha brings significant academic credentials to his practice. He holds a bachelor''s degree in education sciences and two master''s degrees—one in education sciences and another in learning difficulties. This academic foundation leads him to promote capoeira as a valuable educational instrument. He has written short articles about self-understanding and psychomotor skills related to capoeira practice, bridging the gap between physical movement and personal development.',
  E'Marco Herrera começou sua jornada na capoeira em 1998, ingressando no Grupo Zema de Capoeira no Equador sob a instrução de Marco Ayala, que mais tarde se tornaria Mestre Marcos. No ano seguinte, em 1999, recebeu sua primeira corda e o apelido "Perninha"—diminutivo em português de "perna"—que o acompanha desde então.\n\nDesde 1998, Perninha nunca deixou de estar conectado à capoeira, seja através da prática ou do ensino. Como um dos primeiros alunos do Grupo Zema após o retorno de Mestre Zé Maria ao Brasil em 1996, ele fez parte da fundação que Marco Ayala estava construindo para a capoeira equatoriana.\n\nEm dezembro de 2011, Perninha, junto com seus "companheiros e irmãos" Henry Vizcarra (Carvão) e Daniel Herrera (Pandeiro), fundou o Grupo Internacional de Capoeira Centro do Mundo em Quito. A data de fundação foi 17 de dezembro de 2011. O projeto foi endossado e promovido por Mestre Zé Maria, o pioneiro da capoeira no Equador. O Centro do Mundo surgiu com o apoio de outros profissionais de capoeira incluindo os Contramestres Mario Molina e Braulio Rosero (Pantera), bem como os professores Jonathan Chala, Juan Misael Prado (Canguru) e Fernando Hidalgo (Fernandinho 22).\n\nEm maio de 2013, Perninha recebeu a corda branca de mestre de capoeira das mãos de Mestre Zé Maria (José Maria Da Silva) e seu mestre Mestre Paulinho Salmon (Paulo Salmon), ambos do Rio de Janeiro. Esta cerimônia marcou sua entrada em um grupo seleto—ele tem o privilégio e a responsabilidade de ser um dos apenas três mestres equatorianos de capoeira, uma honra compartilhada com Mestre Marcos e Mestre Carvão.\n\nPerninha atua como Diretor Equador do Centro do Mundo, o primeiro grupo de capoeira equatoriano com filiais internacionais nos EUA, Alemanha e Espanha. Ele visitou outras escolas de capoeira tanto no Equador quanto no Brasil para aprender e compartilhar conhecimento, e foi convidado para vários eventos de capoeira para participar, dar workshops e atuar como jurado.\n\nAlém de seu trabalho com capoeira, Perninha traz credenciais acadêmicas significativas para sua prática. Ele possui graduação em ciências da educação e dois mestrados—um em ciências da educação e outro em dificuldades de aprendizagem. Esta formação acadêmica o leva a promover a capoeira como um valioso instrumento educacional. Ele escreveu artigos curtos sobre autoconhecimento e habilidades psicomotoras relacionadas à prática da capoeira, fazendo a ponte entre o movimento físico e o desenvolvimento pessoal.',
  E'- One of only three Ecuadorian mestres of capoeira (with Marcos and Carvão)\n- Co-founded Grupo Internacional de Capoeira Centro do Mundo (December 17, 2011)\n- Director Ecuador of Centro do Mundo\n- Received mestre cord from Zé Maria and Paulinho Salmon (May 2013)\n- Bachelor''s degree in Education Sciences\n- Master''s degree in Education Sciences\n- Master''s degree in Learning Difficulties\n- Published articles on self-understanding and psychomotor skills in capoeira\n- Invited as workshop leader and judge at capoeira events\n- Visited capoeira schools in Ecuador and Brazil for knowledge exchange',
  E'- Um dos apenas três mestres equatorianos de capoeira (com Marcos e Carvão)\n- Cofundador do Grupo Internacional de Capoeira Centro do Mundo (17 de dezembro de 2011)\n- Diretor Equador do Centro do Mundo\n- Recebeu corda de mestre de Zé Maria e Paulinho Salmon (maio de 2013)\n- Graduação em Ciências da Educação\n- Mestrado em Ciências da Educação\n- Mestrado em Dificuldades de Aprendizagem\n- Publicou artigos sobre autoconhecimento e habilidades psicomotoras na capoeira\n- Convidado como instrutor de workshops e jurado em eventos de capoeira\n- Visitou escolas de capoeira no Equador e Brasil para troca de conhecimentos',
  E'BIRTH YEAR:\nNo birth date available in sources. Based on starting capoeira in 1998, likely born ~1975-1985. Insufficient data for estimate.\n\nAPELIDO:\n"Perninha" is Portuguese diminutive of "perna" (leg), meaning "little leg". Received this apelido with his first cord in 1999.\n\nFIRST TEACHER:\nStarted with Marco Ayala (later Mestre Marcos) at Grupo Zema in 1998. Marco Ayala had taken over the school from Mestre Zé Maria in 1996.\n\nTEACHERS:\n- Marco Ayala (Mestre Marcos) - First teacher (1998-ongoing); Grupo Zema de Capoeira; Ecuador\n- Mestre Zé Maria (José Maria Da Silva, 1948-2016) - Grandmaster; pioneer of capoeira in Ecuador; awarded mestre cord (May 2013)\n- Mestre Paulinho Salmon (Paulo Salmon, ~1940-) - Grandmaster; awarded mestre cord with Zé Maria (May 2013)\n\nCO-FOUNDERS OF CENTRO DO MUNDO (December 17, 2011):\n- Carvão (Henry Vizcarra) - Co-founder; later Mestre (May 2013); Director USA\n- Pandeiro (Daniel Herrera) - Co-founder; later Contramestre (2013); Director Spain\n\nSUPPORTING INSTRUCTORS AT FOUNDING:\n- C. Mestre Mario (Mario Molina)\n- C. Mestre Pantera (Braulio Rosero) - Later Director Germany (Freiburg)\n- Prof. Jonathan (Jonathan Chala)\n- Prof. Canguru (Juan Misael Prado)\n- Prof. Fernandinho 22 (Fernando Hidalgo)\n\nECUADORIAN MESTRES (only three):\n- Mestre Marcos (Marco Ayala) - First Ecuadorian mestre (November 2011); Rumizumbi\n- Mestre Carvão (Henry Vizcarra) - May 2013; Centro do Mundo\n- Mestre Perninha (Marco Herrera) - May 2013; Centro do Mundo\n\nACADEMIC BACKGROUND:\n- Bachelor''s degree in Education Sciences\n- Master''s degree in Education Sciences\n- Master''s degree in Learning Difficulties\n- Has written articles on self-understanding and psychomotor skills related to capoeira\n\nEVENTS:\n- Festival Jogando no Centro do Mundo (annual, since May 2012, held in Ecuador and Germany)\n- First Women''s Capoeira Meeting of Ecuador (November 2012)\n- Evento Raíz (first international event, Quito, 2018)\n\nMESTRES WHO HAVE ATTENDED CDM EVENTS:\nZé Maria, Paulinho Salmon, Rui Henrique, Tucano Preto, Duzentos, Bailarino, Coruja',
  E'ANO DE NASCIMENTO:\nNenhuma data de nascimento disponível nas fontes. Com base no início na capoeira em 1998, provavelmente nascido ~1975-1985. Dados insuficientes para estimativa.\n\nAPELIDO:\n"Perninha" é o diminutivo em português de "perna". Recebeu este apelido com sua primeira corda em 1999.\n\nPRIMEIRO PROFESSOR:\nComeçou com Marco Ayala (mais tarde Mestre Marcos) no Grupo Zema em 1998. Marco Ayala havia assumido a escola de Mestre Zé Maria em 1996.\n\nPROFESSORES:\n- Marco Ayala (Mestre Marcos) - Primeiro professor (1998-presente); Grupo Zema de Capoeira; Equador\n- Mestre Zé Maria (José Maria Da Silva, 1948-2016) - Grão-mestre; pioneiro da capoeira no Equador; concedeu corda de mestre (maio de 2013)\n- Mestre Paulinho Salmon (Paulo Salmon, ~1940-) - Grão-mestre; concedeu corda de mestre com Zé Maria (maio de 2013)\n\nCOFUNDADORES DO CENTRO DO MUNDO (17 de dezembro de 2011):\n- Carvão (Henry Vizcarra) - Cofundador; mais tarde Mestre (maio de 2013); Diretor EUA\n- Pandeiro (Daniel Herrera) - Cofundador; mais tarde Contramestre (2013); Diretor Espanha\n\nINSTRUTORES DE APOIO NA FUNDAÇÃO:\n- C. Mestre Mario (Mario Molina)\n- C. Mestre Pantera (Braulio Rosero) - Mais tarde Diretor Alemanha (Freiburg)\n- Prof. Jonathan (Jonathan Chala)\n- Prof. Canguru (Juan Misael Prado)\n- Prof. Fernandinho 22 (Fernando Hidalgo)\n\nMESTRES EQUATORIANOS (apenas três):\n- Mestre Marcos (Marco Ayala) - Primeiro mestre equatoriano (novembro de 2011); Rumizumbi\n- Mestre Carvão (Henry Vizcarra) - Maio de 2013; Centro do Mundo\n- Mestre Perninha (Marco Herrera) - Maio de 2013; Centro do Mundo\n\nFORMAÇÃO ACADÊMICA:\n- Graduação em Ciências da Educação\n- Mestrado em Ciências da Educação\n- Mestrado em Dificuldades de Aprendizagem\n- Escreveu artigos sobre autoconhecimento e habilidades psicomotoras relacionadas à capoeira\n\nEVENTOS:\n- Festival Jogando no Centro do Mundo (anual, desde maio de 2012, realizado no Equador e Alemanha)\n- Primeiro Encontro de Capoeira Feminina do Equador (novembro de 2012)\n- Evento Raíz (primeiro evento internacional, Quito, 2018)\n\nMESTRES QUE PARTICIPARAM DE EVENTOS DO CDM:\nZé Maria, Paulinho Salmon, Rui Henrique, Tucano Preto, Duzentos, Bailarino, Coruja'
)
ON CONFLICT (apelido, COALESCE(apelido_context, '')) WHERE apelido IS NOT NULL DO UPDATE SET
  name = EXCLUDED.name, title = EXCLUDED.title, portrait = EXCLUDED.portrait,
  public_links = EXCLUDED.public_links, style = EXCLUDED.style,
  style_notes_en = EXCLUDED.style_notes_en, style_notes_pt = EXCLUDED.style_notes_pt,
  birth_year = EXCLUDED.birth_year, birth_year_precision = EXCLUDED.birth_year_precision,
  birth_place = EXCLUDED.birth_place, death_year = EXCLUDED.death_year,
  death_year_precision = EXCLUDED.death_year_precision, death_place = EXCLUDED.death_place,
  bio_en = EXCLUDED.bio_en, bio_pt = EXCLUDED.bio_pt,
  achievements_en = EXCLUDED.achievements_en, achievements_pt = EXCLUDED.achievements_pt,
  notes_en = EXCLUDED.notes_en, notes_pt = EXCLUDED.notes_pt, updated_at = NOW();
