-- ============================================================
-- GENEALOGY PERSON: Pierrô
-- Generated: 2025-12-29
-- ============================================================
-- BIRTH YEAR ESTIMATION (~1910, decade precision):
-- If Pierrô was an "elder master" when Mestre Nô arrived in Massaranduba
-- in 1952 at age 7, Pierrô was likely at least 35-45 years old.
-- His teacher Zeca do Uruguai was estimated born ~1900.
-- As a student of Zeca who became an established teacher himself,
-- Pierrô was likely born 5-15 years after Zeca, suggesting ~1910.
-- Using decade precision due to limited documentation.
-- ============================================================

INSERT INTO genealogy.person_profiles (
  name, apelido, title, portrait, public_links,
  style, style_notes_en, style_notes_pt,
  birth_year, birth_year_precision, birth_place,
  death_year, death_year_precision, death_place,
  bio_en, bio_pt, achievements_en, achievements_pt,
  notes_en, notes_pt
) VALUES (
  NULL, 'Pierrô', NULL, NULL,
  ARRAY['https://velhosmestres.com/en/featured-39', 'https://velhosmestres.com/br/destaques-39']::text[],
  'angola'::genealogy.style,
  E'Pierrô was part of the traditional capoeira angola lineage of Salvador''s Cidade Baixa (Lower City). He trained under Mestre Zeca do Uruguai and taught in the space next to Zeca''s house in the Uruguai neighborhood, where students prepared for street rodas. His teaching emphasized the traditional street roda format that characterized Salvador''s Lower City scene before the era of formal academies.',
  E'Pierrô fazia parte da linhagem tradicional de capoeira angola da Cidade Baixa de Salvador. Treinou com Mestre Zeca do Uruguai e ensinava no espaço ao lado da casa de Zeca no bairro do Uruguai, onde os alunos se preparavam para as rodas de rua. Seu ensino enfatizava o formato tradicional de roda de rua que caracterizava a cena da Cidade Baixa de Salvador antes da era das academias formais.',
  1910, 'decade'::genealogy.date_precision, NULL,
  NULL, NULL, NULL,
  E'Pierrô was a capoeirista from the Uruguai neighborhood in Salvador''s Cidade Baixa (Lower City) who played a crucial role in transmitting capoeira angola to the generation that would produce one of the art''s most prolific lineages.\n\nHe learned capoeira under Mestre Zeca do Uruguai, a berimbau master from Santo Amaro da Purificação who had settled in the Uruguai neighborhood. Classes took place in a space next to Zeca''s house, where students trained for the street rodas that formed the backbone of capoeira practice in Salvador''s waterfront communities.\n\nPierrô became one of Zeca''s primary disciples along with Nilton Moraes Paes. Together with Zeca and Nilton, Pierrô organized and commanded many capoeira angola rodas in the streets of the Lower City. This informal network maintained the tradition of street rodas in neighborhoods like Ribeira, Massaranduba, Uruguai, Bonfim, and Jardim Cruzeiro.\n\nHis students included the brothers Nilton (born October 16, 1937) and Cutica (Nelson Moraes Paes, 1941-1970), who lived in nearby Massaranduba and would carry their berimbaus the short walk—not even a kilometer—to train with Pierrô and Zeca in Uruguai.\n\nIn 1952, when seven-year-old Norival Moreira de Oliveira''s family moved to Massaranduba, Nilton and Cutica—by then "highly respected capoeiristas"—took the young boy to meet the elder masters Pierrô and Zeca. This introduction began Norival''s formal capoeira education. On September 18, 1964, Nilton and Cutica awarded Norival his diploma. He became Mestre Nô, the "mestre dos mestres" who has graduated over 75 students to the rank of master—making Pierrô an essential link in one of the most prolific capoeira angola lineages in history.\n\nPierrô''s influence extended beyond the direct line to Mestre Nô. Mestre Vermelho Boxer (Cecílio de Jesus Calheiros, d. 2009), who became one of the most successful capoeiristas in Bahia and Brazil in the 1970s, counted Pierrô among his four main capoeira references, alongside mestres Grande, Lustroso, and João Grande. As a child of 12 in Salvador, Vermelho frequented the neighborhoods of Pelourinho and Cidade Baixa, where he absorbed capoeira in its purest form from these old masters.\n\nPierrô''s dates of birth and death are unknown. His legacy lives through the extensive lineage descending from Mestre Nô and the Capoeira Angola Palmares tradition.',
  E'Pierrô foi um capoeirista do bairro do Uruguai na Cidade Baixa de Salvador que desempenhou papel crucial na transmissão da capoeira angola para a geração que produziria uma das mais prolíficas linhagens da arte.\n\nEle aprendeu capoeira com Mestre Zeca do Uruguai, um mestre de berimbau de Santo Amaro da Purificação que havia se estabelecido no bairro do Uruguai. As aulas aconteciam em um espaço ao lado da casa de Zeca, onde os alunos treinavam para as rodas de rua que formavam a espinha dorsal da prática de capoeira nas comunidades à beira-mar de Salvador.\n\nPierrô tornou-se um dos principais discípulos de Zeca junto com Nilton Moraes Paes. Junto com Zeca e Nilton, Pierrô organizava e comandava muitas rodas de capoeira angola nas ruas da Cidade Baixa. Esta rede informal mantinha a tradição das rodas de rua em bairros como Ribeira, Massaranduba, Uruguai, Bonfim e Jardim Cruzeiro.\n\nSeus alunos incluíam os irmãos Nilton (nascido em 16 de outubro de 1937) e Cutica (Nelson Moraes Paes, 1941-1970), que moravam na vizinha Massaranduba e carregavam seus berimbaus na curta caminhada—nem um quilômetro—para treinar com Pierrô e Zeca no Uruguai.\n\nEm 1952, quando a família de Norival Moreira de Oliveira, de sete anos, se mudou para Massaranduba, Nilton e Cutica—àquela altura "capoeiristas altamente respeitados"—levaram o jovem para conhecer os mestres mais velhos Pierrô e Zeca. Esta apresentação iniciou a educação formal de Norival em capoeira. Em 18 de setembro de 1964, Nilton e Cutica concederam a Norival seu diploma. Ele se tornou Mestre Nô, o "mestre dos mestres" que graduou mais de 75 alunos ao nível de mestre—tornando Pierrô um elo essencial em uma das mais prolíficas linhagens de capoeira angola da história.\n\nA influência de Pierrô se estendeu além da linha direta para Mestre Nô. Mestre Vermelho Boxer (Cecílio de Jesus Calheiros, m. 2009), que se tornou um dos capoeiristas mais bem-sucedidos da Bahia e do Brasil nos anos 1970, contava Pierrô entre suas quatro principais referências de capoeira, ao lado dos mestres Grande, Lustroso e João Grande. Quando criança de 12 anos em Salvador, Vermelho frequentava os bairros do Pelourinho e Cidade Baixa, onde absorveu a capoeira em sua forma mais pura desses velhos mestres.\n\nAs datas de nascimento e morte de Pierrô são desconhecidas. Seu legado vive através da extensa linhagem descendente de Mestre Nô e da tradição da Capoeira Angola Palmares.',
  NULL, NULL,
  E'BIRTH YEAR ESTIMATION (1910, decade):\nIf Pierrô was an "elder master" when Mestre Nô arrived in Massaranduba in 1952 at age 7, Pierrô was likely 35-45+ years old. His teacher Zeca do Uruguai was estimated born ~1900. As an established student-turned-teacher, Pierrô was likely born 5-15 years after Zeca, suggesting ~1905-1915. Using 1910 with decade precision.\n\nNAME VARIATIONS:\n- "Pierrô" - velhosmestres.com (EN/PT), capoeirahub.net (MAJORITY)\n- "Pirró" - lalaue.com, nossa-tribo.com\nUsing "Pierrô" as canonical spelling based on primary source (velhosmestres.com).\n\nTEACHERS:\n- Mestre Zeca do Uruguai (Uruguai neighborhood, Salvador, ~1930s-1940s)\n\nSTUDENTS:\n- Nilton (Nilton Moraes Paes, b. Oct 16, 1937)\n- Cutica (Nelson Moraes Paes, 1941-1970)\n- Mestre Vermelho Boxer (Cecílio de Jesus Calheiros, d. 2009) - as one of four main references\n\nTEACHING LOCATION:\n- Space next to Mestre Zeca''s house, Uruguai neighborhood, Cidade Baixa, Salvador\n\nRODA LOCATIONS:\n- Street rodas in Uruguai neighborhood (organized with Zeca and Nilton)\n- Lower City neighborhoods: Ribeira, Massaranduba, Uruguai, Bonfim, Jardim Cruzeiro\n\nFULL NAME: Unknown. "Pierrô" is a Brazilian adaptation of the French "Pierrot" (diminutive of Pierre/Pedro).\n\nTITLE: While referred to as "Mestre Pierrô" in some sources, formal title conferral not documented. Predates formal academy era.',
  E'ESTIMATIVA DE ANO DE NASCIMENTO (1910, década):\nSe Pierrô era um "mestre mais velho" quando Mestre Nô chegou em Massaranduba em 1952 aos 7 anos, Pierrô provavelmente tinha 35-45+ anos. Seu professor Zeca do Uruguai foi estimado nascido em ~1900. Como aluno estabelecido que se tornou professor, Pierrô provavelmente nasceu 5-15 anos após Zeca, sugerindo ~1905-1915. Usando 1910 com precisão de década.\n\nVARIAÇÕES DE NOME:\n- "Pierrô" - velhosmestres.com (EN/PT), capoeirahub.net (MAIORIA)\n- "Pirró" - lalaue.com, nossa-tribo.com\nUsando "Pierrô" como grafia canônica baseada na fonte primária (velhosmestres.com).\n\nMESTRES:\n- Mestre Zeca do Uruguai (bairro Uruguai, Salvador, ~anos 1930-1940)\n\nALUNOS:\n- Nilton (Nilton Moraes Paes, n. 16 out 1937)\n- Cutica (Nelson Moraes Paes, 1941-1970)\n- Mestre Vermelho Boxer (Cecílio de Jesus Calheiros, m. 2009) - como uma de quatro referências principais\n\nLOCAL DE ENSINO:\n- Espaço ao lado da casa de Mestre Zeca, bairro Uruguai, Cidade Baixa, Salvador\n\nLOCAIS DE RODA:\n- Rodas de rua no bairro Uruguai (organizadas com Zeca e Nilton)\n- Bairros da Cidade Baixa: Ribeira, Massaranduba, Uruguai, Bonfim, Jardim Cruzeiro\n\nNOME COMPLETO: Desconhecido. "Pierrô" é uma adaptação brasileira do francês "Pierrot" (diminutivo de Pierre/Pedro).\n\nTÍTULO: Embora referido como "Mestre Pierrô" em algumas fontes, concessão formal de título não documentada. Precede era das academias formais.'
)
ON CONFLICT (apelido, COALESCE(apelido_context, '')) WHERE apelido IS NOT NULL DO UPDATE SET
  name = EXCLUDED.name, title = EXCLUDED.title, portrait = EXCLUDED.portrait,
  public_links = EXCLUDED.public_links, style = EXCLUDED.style,
  style_notes_en = EXCLUDED.style_notes_en, style_notes_pt = EXCLUDED.style_notes_pt,
  birth_year = EXCLUDED.birth_year, birth_year_precision = EXCLUDED.birth_year_precision,
  birth_place = EXCLUDED.birth_place, death_year = EXCLUDED.death_year,
  death_year_precision = EXCLUDED.death_year_precision, death_place = EXCLUDED.death_place,
  bio_en = EXCLUDED.bio_en, bio_pt = EXCLUDED.bio_pt,
  achievements_en = EXCLUDED.achievements_en, achievements_pt = EXCLUDED.achievements_pt,
  notes_en = EXCLUDED.notes_en, notes_pt = EXCLUDED.notes_pt, updated_at = NOW();
