-- ============================================================
-- GENEALOGY PERSON: Roberto Satanás
-- Generated: 2025-12-20
-- ============================================================
-- Roberto Satanás was a student of Mestre Pastinha at CECA,
-- one of the six capoeiristas who traveled to the 1966 World
-- Festival of Black Arts in Dakar, Senegal, and a singer on
-- Pastinha's 1969 LP. After returning from Senegal, he left
-- capoeira to pursue a career in architecture and karate.
-- ============================================================

INSERT INTO genealogy.person_profiles (
  name, apelido, title, portrait, public_links,
  style, style_notes_en, style_notes_pt,
  birth_year, birth_year_precision, birth_place,
  death_year, death_year_precision, death_place,
  bio_en, bio_pt, achievements_en, achievements_pt,
  notes_en, notes_pt
) VALUES (
  'Roberto Barreto Pereira', 'Roberto Satanás', NULL, NULL,
  ARRAY[
    'https://velhosmestres.com/en/featured-63',
    'https://velhosmestres.com/br/destaques-63'
  ]::text[],
  'angola'::genealogy.style, NULL, NULL,
  1943, 'exact'::genealogy.date_precision, 'Salvador, Bahia, Brazil',
  NULL, NULL, NULL,
  E'Roberto Barreto Pereira, known as Roberto Satanás, was born on December 23, 1943, in Salvador, Bahia, to Alexandre Pereira and Dona Magnólia Barreto Pereira. He joined Mestre Pastinha''s Centro Esportivo de Capoeira Angola (CECA) on September 20, 1960, becoming part of the academy''s golden generation of students.\n\nWithin three years of enrollment, Roberto Satanás demonstrated sufficient mastery to receive his diploma from Mestre Pastinha on March 31, 1963. That same year, he began appearing in photographs documenting the academy''s activities and performances.\n\nIn 1961, Roberto Satanás participated in the TV show "Grande Ginkana Kibon" in Rio de Janeiro alongside other Bahian capoeiristas, bringing Capoeira Angola to a national television audience. He appeared in photographs from the Folklore Congress in Belo Horizonte in 1964, and was featured in Pastinha''s seminal 1965 book.\n\nThe pinnacle of Roberto Satanás''s capoeira career came in April 1966, when he was selected as one of six capoeiristas to accompany Mestre Pastinha to the First World Festival of Black Arts in Dakar, Senegal. The delegation included Mestres João Grande, Gildo Alfinete, Gato Preto, and Camafeu de Oxóssi. When the 77-year-old, nearly blind Pastinha struggled to climb the stairs at Piedade to obtain his passport, Roberto Satanás and Gildo Alfinete helped him climb the stairs.\n\nAt the Dakar festival, Pastinha was too frail to play. Instead, his students - Gato, Roberto, and Gildo - performed while Camafeu played the berimbau. Their presentation was met with tremendous applause from the African audience, representing a symbolic return of capoeira to its continental roots.\n\nIn 1969, Roberto Satanás was one of the singers on Mestre Pastinha''s historic LP "Capoeira Angola - Mestre Pastinha e sua Academia," recorded live at Teatro Castro Alves in Salvador alongside Pastinha and Waldomiro Malvadeza.\n\nRemarkably, shortly after the triumphant Dakar journey, Roberto Satanás left capoeira entirely. He pursued higher education, graduating in architecture, and later became a karate master. On September 24, 1970, he co-founded ARKA Empreendimentos Ltd., and by 2014 was serving as President of the Bidding Committee of DERBA (Bahia''s Department of Transportation Infrastructure).\n\nRoberto Satanás represents a fascinating figure in capoeira history - a highly skilled practitioner who participated in some of the art''s most significant historical moments before choosing a different path in life.',
  E'Roberto Barreto Pereira, conhecido como Roberto Satanás, nasceu em 23 de dezembro de 1943, em Salvador, Bahia, filho de Alexandre Pereira e Dona Magnólia Barreto Pereira. Ele ingressou no Centro Esportivo de Capoeira Angola (CECA) de Mestre Pastinha em 20 de setembro de 1960, tornando-se parte da geração de ouro de alunos da academia.\n\nEm três anos de matrícula, Roberto Satanás demonstrou maestria suficiente para receber seu diploma de Mestre Pastinha em 31 de março de 1963. No mesmo ano, começou a aparecer em fotografias documentando as atividades e apresentações da academia.\n\nEm 1961, Roberto Satanás participou do programa de TV "Grande Ginkana Kibon" no Rio de Janeiro junto com outros capoeiristas baianos, levando a Capoeira Angola para uma audiência televisiva nacional. Ele apareceu em fotografias do Congresso de Folclore em Belo Horizonte em 1964, e foi destaque no livro seminal de Pastinha em 1965.\n\nO auge da carreira de capoeira de Roberto Satanás veio em abril de 1966, quando foi selecionado como um dos seis capoeiristas para acompanhar Mestre Pastinha ao Primeiro Festival Mundial de Artes Negras em Dacar, Senegal. A delegação incluía os Mestres João Grande, Gildo Alfinete, Gato Preto e Camafeu de Oxóssi. Quando o Pastinha de 77 anos, quase cego, teve dificuldades para subir as escadas na Piedade para obter seu passaporte, Roberto Satanás e Gildo Alfinete ajudaram-no a subir as escadas.\n\nNo festival de Dacar, Pastinha estava fraco demais para jogar. Em vez disso, seus alunos - Gato, Roberto e Gildo - se apresentaram enquanto Camafeu tocava o berimbau. A apresentação foi recebida com tremendo aplauso do público africano, representando um retorno simbólico da capoeira às suas raízes continentais.\n\nEm 1969, Roberto Satanás foi um dos cantores no histórico LP de Mestre Pastinha "Capoeira Angola - Mestre Pastinha e sua Academia," gravado ao vivo no Teatro Castro Alves em Salvador, junto com Pastinha e Waldomiro Malvadeza.\n\nNotavelmente, pouco depois da triunfante viagem a Dacar, Roberto Satanás deixou a capoeira completamente. Ele buscou educação superior, formando-se em arquitetura, e mais tarde tornou-se mestre de karatê. Em 24 de setembro de 1970, ele co-fundou a ARKA Empreendimentos Ltda., e em 2014 estava servindo como Presidente da Comissão de Licitação do DERBA (Departamento de Infraestrutura de Transportes da Bahia).\n\nRoberto Satanás representa uma figura fascinante na história da capoeira - um praticante altamente habilidoso que participou de alguns dos momentos históricos mais significativos da arte antes de escolher um caminho diferente na vida.',
  E'Member of the Brazilian delegation to the First World Festival of Black Arts, Dakar, Senegal (1966)\nSinger on Mestre Pastinha''s LP "Capoeira Angola" (1969)\nReceived diploma from Mestre Pastinha (1963)\nParticipated in TV show "Grande Ginkana Kibon" (1961)\nFeatured in Folklore Congress, Belo Horizonte (1964)',
  E'Membro da delegação brasileira ao Primeiro Festival Mundial de Artes Negras, Dacar, Senegal (1966)\nCantor no LP de Mestre Pastinha "Capoeira Angola" (1969)\nRecebeu diploma de Mestre Pastinha (1963)\nParticipou do programa de TV "Grande Ginkana Kibon" (1961)\nDestaque no Congresso de Folclore, Belo Horizonte (1964)',
  E'TEACHERS:\n- Mestre Pastinha (CECA, admitted September 20, 1960; diploma March 31, 1963)\n\nTRAINING COMPANIONS:\n- João Grande (Dakar 1966, CECA)\n- Gildo Alfinete (Dakar 1966, CECA, helped Pastinha climb stairs at Piedade)\n- Gato Preto (Dakar 1966, CECA)\n- Camafeu de Oxóssi (Dakar 1966, played berimbau)\n\nMEDIA APPEARANCES:\n- 1961: TV show "Grande Ginkana Kibon" (Rio de Janeiro)\n- 1964: Folklore Congress photographs (Belo Horizonte)\n- 1965: Featured in Mestre Pastinha''s book\n- 1966: First World Festival of Black Arts (Dakar, Senegal) - performed as player\n- 1969: Singer on LP "Capoeira Angola" (Teatro Castro Alves, Salvador)\n\nPOST-CAPOEIRA CAREER:\n- Left capoeira after returning from Senegal (1966)\n- Graduated in architecture\n- Became karate master\n- Co-founded ARKA Empreendimentos Ltd. (September 24, 1970)\n- President, Bidding Committee of DERBA (2014)\n\nPARENTS:\n- Father: Alexandre Pereira\n- Mother: Dona Magnólia Barreto Pereira\n\nNOTE: No evidence of death date found; appears to have been alive as of 2014.',
  E'MESTRES:\n- Mestre Pastinha (CECA, admitido em 20 de setembro de 1960; diploma em 31 de março de 1963)\n\nCOMPANHEIROS DE TREINO:\n- João Grande (Dacar 1966, CECA)\n- Gildo Alfinete (Dacar 1966, CECA, ajudou Pastinha a subir as escadas na Piedade)\n- Gato Preto (Dacar 1966, CECA)\n- Camafeu de Oxóssi (Dacar 1966, tocou berimbau)\n\nAPARIÇÕES NA MÍDIA:\n- 1961: Programa de TV "Grande Ginkana Kibon" (Rio de Janeiro)\n- 1964: Fotografias do Congresso de Folclore (Belo Horizonte)\n- 1965: Destaque no livro de Mestre Pastinha\n- 1966: Primeiro Festival Mundial de Artes Negras (Dacar, Senegal) - apresentou-se como jogador\n- 1969: Cantor no LP "Capoeira Angola" (Teatro Castro Alves, Salvador)\n\nCARREIRA PÓS-CAPOEIRA:\n- Deixou a capoeira após retornar do Senegal (1966)\n- Formou-se em arquitetura\n- Tornou-se mestre de karatê\n- Co-fundou ARKA Empreendimentos Ltda. (24 de setembro de 1970)\n- Presidente da Comissão de Licitação do DERBA (2014)\n\nPAIS:\n- Pai: Alexandre Pereira\n- Mãe: Dona Magnólia Barreto Pereira\n\nNOTA: Nenhuma evidência de data de falecimento encontrada; parece ter estado vivo em 2014.'
)
ON CONFLICT (apelido, COALESCE(apelido_context, '')) WHERE apelido IS NOT NULL DO UPDATE SET
  name = EXCLUDED.name, title = EXCLUDED.title, portrait = EXCLUDED.portrait,
  public_links = EXCLUDED.public_links, style = EXCLUDED.style,
  style_notes_en = EXCLUDED.style_notes_en, style_notes_pt = EXCLUDED.style_notes_pt,
  birth_year = EXCLUDED.birth_year, birth_year_precision = EXCLUDED.birth_year_precision,
  birth_place = EXCLUDED.birth_place, death_year = EXCLUDED.death_year,
  death_year_precision = EXCLUDED.death_year_precision, death_place = EXCLUDED.death_place,
  bio_en = EXCLUDED.bio_en, bio_pt = EXCLUDED.bio_pt,
  achievements_en = EXCLUDED.achievements_en, achievements_pt = EXCLUDED.achievements_pt,
  notes_en = EXCLUDED.notes_en, notes_pt = EXCLUDED.notes_pt, updated_at = NOW();
