-- ============================================================
-- GENEALOGY PERSON: Tico
-- Generated: 2026-01-11
-- ============================================================
-- BIRTH YEAR ESTIMATION (1870, decade):
-- Tico was active at Cais Dourado in the late 19th/early 20th century,
-- alongside contemporaries like Antônio Corró (b.1870), Besouro Mangangá
-- (b.1895-1900), and Pedro Porreta (b.~1880s). As a dock worker who was
-- already documented in police records during this period, he was likely
-- born around 1870, give or take a decade. This would place him in the
-- same generation as Antônio Corró and slightly older than Besouro.
-- ============================================================

INSERT INTO genealogy.person_profiles (
  name, apelido, title, portrait, public_links,
  style, style_notes_en, style_notes_pt,
  birth_year, birth_year_precision, birth_place,
  death_year, death_year_precision, death_place,
  bio_en, bio_pt, achievements_en, achievements_pt,
  notes_en, notes_pt
) VALUES (
  'Julio dos Santos Menezes', 'Tico', NULL, NULL,
  ARRAY['https://www.mapadacapoeira.com.br/descricaopontos.aspx?fk_ponto=23']::text[],
  NULL, NULL, NULL,
  1870, 'decade'::genealogy.date_precision, 'Santo Amaro, Bahia, Brazil',
  NULL, NULL, NULL,
  E'Julio dos Santos Menezes, known as Tico, was a dock worker and capoeirista from Santo Amaro in the Recôncavo Baiano region who became part of the legendary community of capoeiristas at the Cais Dourado (Golden Wharf) in Salvador during the late 19th and early 20th centuries.\n\nTico worked as a carregador (porter) and frequented the Freguesia do Pilar, the parish that encompassed the waterfront district where dock workers, stevedores, and saveiristas congregated. The Cais Dourado was notorious as a stronghold of capoeira—a universe of maritime laborers who breathed the culture of sailors in their daily lives and practiced their art amid the bustle of commerce and cargo.\n\nThe historical record captures Tico through a violent incident: he was arrested following an armed confrontation in which he wielded a faca de sapateiro (shoemaker''s knife) against "Martins'' group." The fight left him with cuts to his arms, face, and hands. This documentation, likely from police records, is typical of how Layer Zero capoeiristas entered the historical record—not through celebrations of their art, but through encounters with authorities during the era of criminalization.\n\nTico''s contemporaries at the Cais Dourado included some of the most storied names in early capoeira: the legendary Besouro Mangangá who arrived from Santo Amaro via saveiro, Pedro Porreta the fish seller who dominated the Baixa dos Sapateiros, Caboclinho the saveirista, and Antônio Corró the cart driver who would later teach Mestre Paraná. Together they formed a community of working-class practitioners who kept capoeira alive through the years of prohibition, meeting at the waterfront, at the Mercado Santa Bárbara, and during festivals like the Santa Luzia celebration documented by Mestre Noronha in 1922.\n\nLike many of his generation, Tico''s fate after the early 20th century is unknown. He remains one of the anonymous ancestors—African and Afro-Brazilian workers who preserved and transmitted the art during its most dangerous years.',
  E'Julio dos Santos Menezes, conhecido como Tico, foi um trabalhador portuário e capoeirista de Santo Amaro, no Recôncavo Baiano, que fez parte da lendária comunidade de capoeiristas do Cais Dourado em Salvador durante o final do século XIX e início do século XX.\n\nTico trabalhava como carregador e frequentava a Freguesia do Pilar, a paróquia que abrangia o distrito portuário onde estivadores, trabalhadores de cais e saveiristas se congregavam. O Cais Dourado era notório como um reduto da capoeira—um universo de trabalhadores marítimos que respiravam a cultura dos marinheiros em seu cotidiano e praticavam sua arte em meio à agitação do comércio e da carga.\n\nO registro histórico captura Tico através de um incidente violento: ele foi preso após um confronto armado no qual empunhou uma faca de sapateiro contra o "grupo de Martins". A briga deixou-o com cortes nos braços, rosto e mãos. Esta documentação, provavelmente de registros policiais, é típica de como os capoeiristas da Camada Zero entraram no registro histórico—não através de celebrações de sua arte, mas através de encontros com as autoridades durante a era de criminalização.\n\nOs contemporâneos de Tico no Cais Dourado incluíam alguns dos nomes mais célebres da capoeira antiga: o lendário Besouro Mangangá que chegava de Santo Amaro via saveiro, Pedro Porreta o vendedor de peixe que dominava a Baixa dos Sapateiros, Caboclinho o saveirista, e Antônio Corró o carroceiro que mais tarde ensinaria Mestre Paraná. Juntos, eles formavam uma comunidade de praticantes da classe trabalhadora que mantiveram a capoeira viva durante os anos de proibição, reunindo-se no cais, no Mercado Santa Bárbara, e durante festivais como a celebração de Santa Luzia documentada por Mestre Noronha em 1922.\n\nComo muitos de sua geração, o destino de Tico após o início do século XX é desconhecido. Ele permanece como um dos ancestrais anônimos—trabalhadores africanos e afro-brasileiros que preservaram e transmitiram a arte durante seus anos mais perigosos.',
  E'One of the documented capoeiristas of the Cais Dourado in Salvador\nPart of the Santo Amaro-to-Salvador capoeira migration pattern\nContemporary of Besouro Mangangá, Pedro Porreta, Caboclinho, and Antônio Corró',
  E'Um dos capoeiristas documentados do Cais Dourado em Salvador\nParte do padrão migratório de capoeira Santo Amaro-Salvador\nContemporâneo de Besouro Mangangá, Pedro Porreta, Caboclinho e Antônio Corró',
  E'BIRTH YEAR ESTIMATION (1870, decade):\nActive at Cais Dourado late 19th/early 20th century. Contemporary of Antônio Corró (b.1870), slightly older generation than Besouro (b.1895-1900). Estimated 1870 ± decade based on working-age during documentation period.\n\nNAME: Full name confirmed as Julio dos Santos Menezes from Mapa da Capoeira source.\n\nOCCUPATION: Carregador (porter) at the docks. Frequented Freguesia do Pilar parish.\n\nDOCUMENTED INCIDENT:\nArrested after armed confrontation using "faca de sapateiro" (shoemaker''s knife) against "Martins'' group." Sustained cuts to arms, face, and hands. Source: Police/arrest records cited in Mapa da Capoeira.\n\nCONTEMPORARIES AT CAIS DOURADO:\n- Besouro de Mangangá (arrived from Santo Amaro via saveiro)\n- Pedro Porreta (fish seller, dominated Baixa dos Sapateiros)\n- Caboclinho (Alfredo Martins Teixeira, saveirista)\n- Antônio Corró (cart driver, later teacher of Mestre Paraná)\n- Mata Escura, Manoel Thié, Marinheiro, Mangue Sêco\n- Ignácio Loyola, Pedro Piroca, Pedro Mineiro\n- Antonio Boca de Porco, Gabiano, Agripino\n- Paulo Gomes, José Martins, Cypriano, Três Pedaços\n\nLOCATION DETAIL:\nCais Dourado (Golden Wharf) - waterfront area in Pilar district, Salvador. Hub for dock workers, stevedores, saveiristas. Site of frequent clashes between capoeiristas and police.',
  E'ESTIMATIVA DE ANO DE NASCIMENTO (1870, década):\nAtivo no Cais Dourado no final do século XIX/início do XX. Contemporâneo de Antônio Corró (n.1870), geração ligeiramente mais velha que Besouro (n.1895-1900). Estimado 1870 ± década baseado na idade de trabalho durante o período documentado.\n\nNOME: Nome completo confirmado como Julio dos Santos Menezes pela fonte Mapa da Capoeira.\n\nOCUPAÇÃO: Carregador no porto. Frequentava a Freguesia do Pilar.\n\nINCIDENTE DOCUMENTADO:\nPreso após confronto armado usando "faca de sapateiro" contra o "grupo de Martins". Sofreu cortes nos braços, rosto e mãos. Fonte: Registros policiais/de prisão citados no Mapa da Capoeira.\n\nCONTEMPORÂNEOS NO CAIS DOURADO:\n- Besouro de Mangangá (chegava de Santo Amaro via saveiro)\n- Pedro Porreta (vendedor de peixe, dominava a Baixa dos Sapateiros)\n- Caboclinho (Alfredo Martins Teixeira, saveirista)\n- Antônio Corró (carroceiro, mais tarde mestre de Mestre Paraná)\n- Mata Escura, Manoel Thié, Marinheiro, Mangue Sêco\n- Ignácio Loyola, Pedro Piroca, Pedro Mineiro\n- Antonio Boca de Porco, Gabiano, Agripino\n- Paulo Gomes, José Martins, Cypriano, Três Pedaços\n\nDETALHE DE LOCALIZAÇÃO:\nCais Dourado (Cais Dourado) - área portuária no distrito do Pilar, Salvador. Centro para estivadores, trabalhadores de cais, saveiristas. Local de frequentes confrontos entre capoeiristas e polícia.'
)
ON CONFLICT (apelido, COALESCE(apelido_context, '')) WHERE apelido IS NOT NULL DO UPDATE SET
  name = EXCLUDED.name, title = EXCLUDED.title, portrait = EXCLUDED.portrait,
  public_links = EXCLUDED.public_links, style = EXCLUDED.style,
  style_notes_en = EXCLUDED.style_notes_en, style_notes_pt = EXCLUDED.style_notes_pt,
  birth_year = EXCLUDED.birth_year, birth_year_precision = EXCLUDED.birth_year_precision,
  birth_place = EXCLUDED.birth_place, death_year = EXCLUDED.death_year,
  death_year_precision = EXCLUDED.death_year_precision, death_place = EXCLUDED.death_place,
  bio_en = EXCLUDED.bio_en, bio_pt = EXCLUDED.bio_pt,
  achievements_en = EXCLUDED.achievements_en, achievements_pt = EXCLUDED.achievements_pt,
  notes_en = EXCLUDED.notes_en, notes_pt = EXCLUDED.notes_pt, updated_at = NOW();
