-- ============================================================
-- GENEALOGY PERSON: Vinte e Nove
-- Generated: 2025-12-26
-- ============================================================
-- BIRTH YEAR ESTIMATION (1920, decade precision):
-- Active as a recognized mestre in Salvador in 1982 (O Globo article).
-- Contemporary of other Bimba disciples like Brás Amansa Brabo (est. ~1920)
-- and Vermelho 27 (1936-1996). If he trained with Bimba in the 1940s-1950s
-- as a young adult (teens to early 20s), birth would be approximately
-- 1915-1935. Using 1925 as central estimate with decade precision.
-- This would make him approximately 57 years old in 1982.
-- ============================================================

INSERT INTO genealogy.person_profiles (
  name, apelido, title, portrait, public_links,
  style, style_notes_en, style_notes_pt,
  birth_year, birth_year_precision, birth_place,
  death_year, death_year_precision, death_place,
  bio_en, bio_pt, achievements_en, achievements_pt,
  notes_en, notes_pt
) VALUES (
  NULL, 'Vinte e Nove', 'mestre'::genealogy.title, NULL,
  ARRAY['https://velhosmestres.com/br/cobrinha-1982-3', 'http://velhosmestres.com/en/cobrinha-1982-3']::text[],
  'regional'::genealogy.style,
  E'Trained directly under Mestre Bimba in the Capoeira Regional tradition. Part of the core group of Regional mestres active in Salvador during the late 20th century.',
  E'Treinado diretamente com Mestre Bimba na tradição da Capoeira Regional. Parte do grupo central de mestres Regional ativos em Salvador durante o final do século XX.',
  1925, 'decade'::genealogy.date_precision, NULL,
  NULL, NULL, NULL,
  E'Mestre Vinte e Nove was a direct disciple of Mestre Bimba, the founder of Capoeira Regional. His apelido—meaning "Twenty-Nine" in Portuguese—likely derives from the jogo do bicho, the popular Brazilian numbers game where 29 represents the Camelo (Camel), a symbol of endurance and resilience. Such number-based nicknames were common among capoeiristas of his era in Salvador, with his contemporary Vermelho 27 carrying a similar numerical apelido.\n\nThe historical record places Vinte e Nove among the most prominent Capoeira Regional mestres of his generation. In February 1982, O Globo newspaper published an article titled "Capoeira - Uma grande polêmica nas rodas baianas" (Capoeira - A great controversy in the Bahia rodas), documenting the state of capoeira in Salvador. The article surveyed the capoeira landscape by lineage, identifying the leading figures in each tradition. For the "regional" branch, it noted that "almost all were direct disciples of the legendary Bimba", and specifically named Vinte e Nove among the most distinguished mestres. He appears in this documentation alongside Itapuã, Brás Amansa Brabo, Vermelho 27, Medicina, Banduê, Capazans, Ezequiel, and Hélio Xaréu.\n\nThis 1982 press coverage confirms that Vinte e Nove had achieved recognition as a mestre and was actively teaching and participating in the Salvador capoeira community at that time. His inclusion in this select list of "prominent" regional mestres indicates he was considered among the leading practitioners carrying forward Bimba''s legacy.\n\nBeyond this documentation, little else has been preserved about his life. His full name, precise birth and death dates, the details of his training timeline with Bimba, and information about his own students remain undocumented in available sources. Like several of his contemporaries named in the 1982 article, Vinte e Nove represents a mestre whose individual story has been overshadowed by the more extensively documented figures of the Regional lineage. His presence in this significant press coverage, however, confirms his historical importance as one of the direct links in the chain connecting Mestre Bimba to subsequent generations of Capoeira Regional.',
  E'Mestre Vinte e Nove foi discípulo direto de Mestre Bimba, o fundador da Capoeira Regional. Seu apelido—significando "Vinte e Nove" em português—provavelmente deriva do jogo do bicho, o popular jogo de números brasileiro onde 29 representa o Camelo, símbolo de resistência e resiliência. Tais apelidos baseados em números eram comuns entre capoeiristas de sua época em Salvador, com seu contemporâneo Vermelho 27 carregando um apelido numérico similar.\n\nO registro histórico coloca Vinte e Nove entre os mais proeminentes mestres de Capoeira Regional de sua geração. Em fevereiro de 1982, o jornal O Globo publicou um artigo intitulado "Capoeira - Uma grande polêmica nas rodas baianas", documentando o estado da capoeira em Salvador. O artigo pesquisou o panorama da capoeira por linhagem, identificando as figuras principais em cada tradição. Para o ramo "regional", observou que "quase todos eram discípulos diretos do lendário Bimba", e nomeou especificamente Vinte e Nove entre os mestres mais distintos. Ele aparece nesta documentação ao lado de Itapuã, Brás Amansa Brabo, Vermelho 27, Medicina, Banduê, Capazans, Ezequiel e Hélio Xaréu.\n\nEsta cobertura de imprensa de 1982 confirma que Vinte e Nove havia alcançado reconhecimento como mestre e estava ativamente ensinando e participando da comunidade de capoeira de Salvador naquela época. Sua inclusão nesta lista seleta de mestres regional "proeminentes" indica que ele era considerado entre os principais praticantes que levavam adiante o legado de Bimba.\n\nAlém desta documentação, pouco mais foi preservado sobre sua vida. Seu nome completo, datas precisas de nascimento e morte, os detalhes de sua linha do tempo de treinamento com Bimba, e informações sobre seus próprios alunos permanecem não documentados nas fontes disponíveis. Como vários de seus contemporâneos nomeados no artigo de 1982, Vinte e Nove representa um mestre cuja história individual foi ofuscada por figuras mais extensivamente documentadas da linhagem Regional. Sua presença nesta significativa cobertura de imprensa, no entanto, confirma sua importância histórica como um dos elos diretos na corrente conectando Mestre Bimba às gerações subsequentes de Capoeira Regional.',
  E'Direct disciple of Mestre Bimba\nRecognized as prominent Regional mestre in Salvador (documented 1982)\nNamed alongside Itapuã, Vermelho 27, Brás Amansa Brabo and other leading Regional mestres',
  E'Discípulo direto de Mestre Bimba\nReconhecido como mestre Regional proeminente em Salvador (documentado 1982)\nNomeado ao lado de Itapuã, Vermelho 27, Brás Amansa Brabo e outros mestres Regional destacados',
  E'BIRTH YEAR ESTIMATION (1925, decade precision):\nActive as recognized mestre in Salvador in 1982 (O Globo article). Contemporary of other Bimba disciples like Brás Amansa Brabo (est. ~1920) and Vermelho 27 (1936-1996). If he trained with Bimba in the 1940s-1950s as a young adult, birth approximately 1915-1935. Using 1925 as central estimate. This would make him approximately 57 years old in 1982.\n\nTEACHERS:\n- Mestre Bimba (Manoel dos Reis Machado) - primary teacher, direct disciple\n\nSTUDENTS:\n- Unknown\n\nCONTEMPORARIES (1982 O Globo Article):\n- Mestre Itapuã (Raimundo César Alves de Almeida)\n- Mestre Brás Amansa Brabo\n- Mestre Vermelho 27 (José Carlos Andrade Bittencourt)\n- Mestre Medicina\n- Mestre Banduê\n- Mestre Capazans\n- Mestre Ezequiel (Eziquiel Martins Marinho)\n- Mestre Hélio Xaréu (Hélio Campos)\n\nAPELIDO MEANING:\n"Vinte e Nove" (Twenty-Nine) likely derives from the jogo do bicho, where 29 is associated with the Camelo (Camel), symbolizing endurance and resilience. Number-based apelidos were common among Salvador capoeiristas of this era (cf. Vermelho 27).\n\nLIMITED DOCUMENTATION:\nThis profile is based primarily on one source: O Globo newspaper article (February 16, 1982) archived on velhosmestres.com. No other biographical details were found during research.',
  E'ESTIMATIVA DE ANO DE NASCIMENTO (1925, precisão de década):\nAtivo como mestre reconhecido em Salvador em 1982 (artigo O Globo). Contemporâneo de outros discípulos de Bimba como Brás Amansa Brabo (est. ~1920) e Vermelho 27 (1936-1996). Se treinou com Bimba nos anos 1940-1950 como jovem adulto, nascimento aproximadamente 1915-1935. Usando 1925 como estimativa central. Isso o faria aproximadamente 57 anos em 1982.\n\nMESTRES:\n- Mestre Bimba (Manoel dos Reis Machado) - professor principal, discípulo direto\n\nALUNOS:\n- Desconhecido\n\nCONTEMPORÂNEOS (Artigo O Globo 1982):\n- Mestre Itapuã (Raimundo César Alves de Almeida)\n- Mestre Brás Amansa Brabo\n- Mestre Vermelho 27 (José Carlos Andrade Bittencourt)\n- Mestre Medicina\n- Mestre Banduê\n- Mestre Capazans\n- Mestre Ezequiel (Eziquiel Martins Marinho)\n- Mestre Hélio Xaréu (Hélio Campos)\n\nSIGNIFICADO DO APELIDO:\n"Vinte e Nove" provavelmente deriva do jogo do bicho, onde 29 está associado ao Camelo, simbolizando resistência e resiliência. Apelidos baseados em números eram comuns entre capoeiristas de Salvador desta época (cf. Vermelho 27).\n\nDOCUMENTAÇÃO LIMITADA:\nEste perfil é baseado principalmente em uma fonte: artigo do jornal O Globo (16 de fevereiro de 1982) arquivado em velhosmestres.com. Nenhum outro detalhe biográfico foi encontrado durante a pesquisa.'
)
ON CONFLICT (apelido, COALESCE(apelido_context, '')) WHERE apelido IS NOT NULL DO UPDATE SET
  name = EXCLUDED.name, title = EXCLUDED.title, portrait = EXCLUDED.portrait,
  public_links = EXCLUDED.public_links, style = EXCLUDED.style,
  style_notes_en = EXCLUDED.style_notes_en, style_notes_pt = EXCLUDED.style_notes_pt,
  birth_year = EXCLUDED.birth_year, birth_year_precision = EXCLUDED.birth_year_precision,
  birth_place = EXCLUDED.birth_place, death_year = EXCLUDED.death_year,
  death_year_precision = EXCLUDED.death_year_precision, death_place = EXCLUDED.death_place,
  bio_en = EXCLUDED.bio_en, bio_pt = EXCLUDED.bio_pt,
  achievements_en = EXCLUDED.achievements_en, achievements_pt = EXCLUDED.achievements_pt,
  notes_en = EXCLUDED.notes_en, notes_pt = EXCLUDED.notes_pt, updated_at = NOW();
