-- ============================================================
-- GENEALOGY PERSON: Zeca (Gato Preto)
-- Generated: 2026-01-10
-- Primary Source: https://capoeirawiki.org/wiki/Mestre_Zeca
-- ============================================================
-- DEPENDENCIES: gato-preto.sql (father/primary teacher),
--               canjiquinha.sql, caicara.sql (trained alongside)
-- ============================================================
--
-- BIRTH PLACE DISCREPANCY:
-- CapoeiraWiki states birthplace as "Botafogo, Rio de Janeiro, Brazil"
-- However, his father Gato Preto was based in Santo Amaro/Salvador.
-- The family performed in Brasília in 1969, suggesting they traveled.
-- Using CapoeiraWiki's location as primary source.
--
-- NAMING DISAMBIGUATION:
-- - "Zeca" is his mestre name
-- - "Gatinho" was his childhood nickname
-- - "Gato III" references his place in the Gato lineage (after Gato Preto and Gato II)
-- Uses apelido_context 'Gato Preto' to distinguish from other Zecas
-- (Zeca do Uruguai, Zeca Floriano already in database)
--
-- DEATH: March 25, 2024 - confirmed by CapoeiraWiki and velhosmestres.com
--
-- ============================================================

INSERT INTO genealogy.person_profiles (
  name, apelido, apelido_context, title, portrait, public_links,
  style, style_notes_en, style_notes_pt,
  birth_year, birth_year_precision, birth_place,
  death_year, death_year_precision, death_place,
  bio_en, bio_pt, achievements_en, achievements_pt,
  notes_en, notes_pt
) VALUES (
  'José Souza Góes',
  'Zeca',
  'Gato Preto',
  'mestre'::genealogy.title,
  NULL,
  ARRAY['https://capoeirawiki.org/wiki/Mestre_Zeca', 'https://velhosmestres.com/br/gatopreto']::text[],
  'angola'::genealogy.style,
  E'Mestre Zeca was a pure angoleiro who conceptualized capoeira as "geometria aplicada" (applied geometry), emphasizing spatial composition and angular awareness. He advocated strongly for preserving traditional jogos: Angola, São Bento Grande, Banguela, Iúna, Cavalaria, and the rarely-practiced Samba de Angola. He viewed the berimbau as a "baton of the maestro"—a communication tool, symbol of authority, and instrument for achieving trance-like immersion. He echoed Jigoro Kano''s principle: "He who says he knows has not even begun to learn."',
  E'Mestre Zeca era um angoleiro puro que conceituava a capoeira como "geometria aplicada", enfatizando composição espacial e consciência angular. Defendia fortemente a preservação dos jogos tradicionais: Angola, São Bento Grande, Banguela, Iúna, Cavalaria e o raramente praticado Samba de Angola. Via o berimbau como um "bastão de maestro"—ferramenta de comunicação, símbolo de autoridade e instrumento para alcançar imersão como em transe. Ecoava o princípio de Jigoro Kano: "Quem diz que sabe ainda não começou a aprender."',
  1956,
  'exact'::genealogy.date_precision,
  'Botafogo, Rio de Janeiro, Brazil',
  2024,
  'exact'::genealogy.date_precision,
  NULL,
  E'José Souza Góes, known as Mestre Zeca, Gatinho, or Gato III, was born on April 16, 1956, in Botafogo, Rio de Janeiro. He was the son of the legendary Mestre Gato Preto (José Gabriel Góes), "O Berimbau de Ouro da Bahia," who had trained under Cobrinha Verde, Pastinha, and Waldemar da Paixão.\n\nZeca began his capoeira training in 1963 at age seven under his father''s guidance. Growing up in the academies of Salvador''s greatest Angola mestres, he trained alongside legendary figures including Mestre Canjiquinha and Mestre Caiçara—an apprenticeship few could claim. By age thirteen, he was already performing publicly.\n\nOn March 26, 1969, the young Zeca appeared at Teatro Martins Penna in Brasília alongside his father and older brother Sinésio (Mestre Gato II). The performance, which included Samba de Roda, pandeiro demonstrations, Maculelê, and Capoeira, marked one of the family''s many cultural presentations. Following this event, the University of Brasília proposed contracting Mestre Gato Preto to teach capoeira.\n\nIn 1974, at age eighteen, Zeca co-founded two important institutions: the Associação de Capoeira 3 Amigos and the Grupo Folclórico Filhos de Oxalá, alongside Mestres Mau and Mala. The 3 Amigos association maintained the Angola lineage, creating a space where the elderly Mestre Cobrinha Verde would feel at home on Sundays.\n\nBy 1976, while still in his twenties, Zeca was overseeing one of his father''s two capoeira academies in Bahia—one on Rua do Báu in Garcia, another in Boca do Rio. He worked alongside Espinho Remoso in managing these schools while his father traveled internationally. That same year, he accompanied Mestre Gato Preto to the "Diáspora Africana" festival in the United States.\n\nThroughout his career, Zeca developed a distinctive philosophical approach to capoeira. He conceptualized the art as "geometria aplicada" (applied geometry), comparing movement to "the spatial composition of paintings." This reflected his understanding of movement, angles, and roda awareness developed over decades of practice.\n\nZeca became a passionate advocate for traditional capoeira styles. He emphasized preserving the classic jogos—Angola, São Bento Grande, Banguela, Iúna, Cavalaria—and the rarely-practiced Samba de Angola, lamenting their decline in modern practice. For Zeca, the berimbau represented more than an instrument: it was a "baton of the maestro," a communication tool, symbol of authority, and instrument for achieving trance-like immersion in the roda.\n\nIn 2002, following his father''s death in August, Zeca visited Grupo Meia Lua in Brasília, maintaining his connections across the capoeira world. He remained active through the 2000s, teaching and advocating for traditional practice.\n\nMestre Zeca died on March 25, 2024, just weeks before his 68th birthday, bringing to a close a lifetime dedicated to capoeira angola and the family tradition established by his father.',
  E'José Souza Góes, conhecido como Mestre Zeca, Gatinho ou Gato III, nasceu em 16 de abril de 1956, em Botafogo, Rio de Janeiro. Era filho do lendário Mestre Gato Preto (José Gabriel Góes), "O Berimbau de Ouro da Bahia," que havia treinado com Cobrinha Verde, Pastinha e Waldemar da Paixão.\n\nZeca começou seu treinamento de capoeira em 1963, aos sete anos, sob a orientação de seu pai. Crescendo nas academias dos maiores mestres de Angola de Salvador, treinou ao lado de figuras lendárias incluindo Mestre Canjiquinha e Mestre Caiçara—uma aprendizagem que poucos podiam reivindicar. Aos treze anos, já se apresentava publicamente.\n\nEm 26 de março de 1969, o jovem Zeca apareceu no Teatro Martins Penna em Brasília ao lado de seu pai e irmão mais velho Sinésio (Mestre Gato II). A apresentação, que incluiu Samba de Roda, demonstrações de pandeiro, Maculelê e Capoeira, marcou uma das muitas apresentações culturais da família. Após este evento, a Universidade de Brasília propôs contratar Mestre Gato Preto para ensinar capoeira.\n\nEm 1974, aos dezoito anos, Zeca co-fundou duas importantes instituições: a Associação de Capoeira 3 Amigos e o Grupo Folclórico Filhos de Oxalá, junto com Mestres Mau e Mala. A associação 3 Amigos mantinha a linhagem Angola, criando um espaço onde o idoso Mestre Cobrinha Verde se sentiria em casa aos domingos.\n\nEm 1976, ainda com vinte e poucos anos, Zeca supervisionava uma das duas academias de capoeira de seu pai na Bahia—uma na Rua do Báu no Garcia, outra na Boca do Rio. Trabalhava ao lado de Espinho Remoso na gestão dessas escolas enquanto seu pai viajava internacionalmente. No mesmo ano, acompanhou Mestre Gato Preto ao festival "Diáspora Africana" nos Estados Unidos.\n\nAo longo de sua carreira, Zeca desenvolveu uma abordagem filosófica distintiva da capoeira. Conceituava a arte como "geometria aplicada," comparando o movimento à "composição espacial de pinturas." Isso refletia sua compreensão de movimento, ângulos e consciência da roda desenvolvida ao longo de décadas de prática.\n\nZeca tornou-se um defensor apaixonado dos estilos tradicionais de capoeira. Enfatizava a preservação dos jogos clássicos—Angola, São Bento Grande, Banguela, Iúna, Cavalaria—e o raramente praticado Samba de Angola, lamentando seu declínio na prática moderna. Para Zeca, o berimbau representava mais que um instrumento: era um "bastão de maestro," uma ferramenta de comunicação, símbolo de autoridade e instrumento para alcançar imersão como em transe na roda.\n\nEm 2002, após a morte de seu pai em agosto, Zeca visitou o Grupo Meia Lua em Brasília, mantendo suas conexões através do mundo da capoeira. Permaneceu ativo durante os anos 2000, ensinando e defendendo a prática tradicional.\n\nMestre Zeca morreu em 25 de março de 2024, poucas semanas antes de seu 68º aniversário, encerrando uma vida dedicada à capoeira angola e à tradição familiar estabelecida por seu pai.',
  E'Co-founder of Associação de Capoeira 3 Amigos (1974) with Mestres Mau and Mala\nCo-founder of Grupo Folclórico Filhos de Oxalá (1974)\nPerformed at Teatro Martins Penna, Brasília (1969) at age 13\nParticipated in "Diáspora Africana" festival, USA (1976)\nManaged his father''s academies in Garcia and Boca do Rio (1970s)\nDeveloped "geometria aplicada" (applied geometry) philosophy of capoeira\nAdvocate for traditional Angola jogos preservation',
  E'Co-fundador da Associação de Capoeira 3 Amigos (1974) com Mestres Mau e Mala\nCo-fundador do Grupo Folclórico Filhos de Oxalá (1974)\nApresentou-se no Teatro Martins Penna, Brasília (1969) aos 13 anos\nParticipou do festival "Diáspora Africana", EUA (1976)\nGeriu as academias de seu pai no Garcia e Boca do Rio (anos 1970)\nDesenvolveu a filosofia da "geometria aplicada" para capoeira\nDefensor da preservação dos jogos tradicionais de Angola',
  E'BIRTH DATE: April 16, 1956 - exact date from CapoeiraWiki.\n\nBIRTH PLACE DISCREPANCY:\n- CapoeiraWiki: Botafogo, Rio de Janeiro, Brazil\n- Father Gato Preto was based in Salvador/Santo Amaro\n- Using CapoeiraWiki as primary source\n\nDEATH DATE: March 25, 2024 - exact, confirmed by CapoeiraWiki and velhosmestres.com.\n\nNAME VARIATIONS:\n- "Zeca" - mestre name\n- "Gatinho" - childhood nickname (means "little cat")\n- "Gato III" - third in Gato lineage after Gato Preto and Gato II (brother Sinésio)\n\nTEACHERS:\n- Mestre Gato Preto (father, primary teacher from 1963)\n- Mestre Canjiquinha (trained alongside as child in academies)\n- Mestre Caiçara (trained alongside as child in academies)\n\nPEERS/CO-FOUNDERS (1974):\n- Mestre Mau (Marcelino dos Santos) - co-founded 3 Amigos and Filhos de Oxalá\n- Mestre Mala - co-founded 3 Amigos and Filhos de Oxalá\n\nFAMILY:\n- Father: Mestre Gato Preto (José Gabriel Góes) - 1930-2002\n- Brother: Mestre Gato II (Sinésio Souza Góes) - born Sept 7, 1950\n\nTRAINING TIMELINE:\n- 1963 (age 7): Began training under father\n- 1969 (age 13): First documented public performance, Teatro Martins Penna, Brasília\n- 1974 (age 18): Co-founded Capoeira 3 Amigos and Filhos de Oxalá\n- 1976 (age 20): Managing father''s academies; traveled to USA for Diáspora Africana\n- 2002: Visited Grupo Meia Lua in Brasília after father''s death\n\nPHILOSOPHY:\n- "Geometria aplicada" (applied geometry) - spatial composition concept\n- Berimbau as "baton of the maestro"\n- Advocate for traditional jogos: Angola, São Bento Grande, Banguela, Iúna, Cavalaria, Samba de Angola\n- Echoed Jigoro Kano: "He who says he knows has not even begun to learn"\n\nMEDIA APPEARANCES:\n- 1969: Teatro Martins Penna, Brasília performance (with father and brother)\n- 2020s: YouTube interview "147ª LIVE NA IDENTIDADE DO CAPOEIRA"',
  E'DATA DE NASCIMENTO: 16 de abril de 1956 - data exata de CapoeiraWiki.\n\nDISCREPÂNCIA DO LOCAL DE NASCIMENTO:\n- CapoeiraWiki: Botafogo, Rio de Janeiro, Brasil\n- Pai Gato Preto era baseado em Salvador/Santo Amaro\n- Usando CapoeiraWiki como fonte primária\n\nDATA DE MORTE: 25 de março de 2024 - exata, confirmada por CapoeiraWiki e velhosmestres.com.\n\nVARIAÇÕES DE NOME:\n- "Zeca" - nome de mestre\n- "Gatinho" - apelido de infância\n- "Gato III" - terceiro na linhagem Gato após Gato Preto e Gato II (irmão Sinésio)\n\nMESTRES:\n- Mestre Gato Preto (pai, professor principal de 1963)\n- Mestre Canjiquinha (treinou junto quando criança nas academias)\n- Mestre Caiçara (treinou junto quando criança nas academias)\n\nPARES/CO-FUNDADORES (1974):\n- Mestre Mau (Marcelino dos Santos) - co-fundou 3 Amigos e Filhos de Oxalá\n- Mestre Mala - co-fundou 3 Amigos e Filhos de Oxalá\n\nFAMÍLIA:\n- Pai: Mestre Gato Preto (José Gabriel Góes) - 1930-2002\n- Irmão: Mestre Gato II (Sinésio Souza Góes) - nascido 7 set 1950\n\nCRONOLOGIA DE TREINAMENTO:\n- 1963 (7 anos): Começou treinamento com o pai\n- 1969 (13 anos): Primeira apresentação pública documentada, Teatro Martins Penna, Brasília\n- 1974 (18 anos): Co-fundou Capoeira 3 Amigos e Filhos de Oxalá\n- 1976 (20 anos): Gerindo as academias do pai; viajou aos EUA para Diáspora Africana\n- 2002: Visitou Grupo Meia Lua em Brasília após a morte do pai\n\nFILOSOFIA:\n- "Geometria aplicada" - conceito de composição espacial\n- Berimbau como "bastão do maestro"\n- Defensor dos jogos tradicionais: Angola, São Bento Grande, Banguela, Iúna, Cavalaria, Samba de Angola\n- Ecoava Jigoro Kano: "Quem diz que sabe ainda não começou a aprender"\n\nAPARIÇÕES NA MÍDIA:\n- 1969: Apresentação Teatro Martins Penna, Brasília (com pai e irmão)\n- Anos 2020: Entrevista no YouTube "147ª LIVE NA IDENTIDADE DO CAPOEIRA"'
)
ON CONFLICT (apelido, COALESCE(apelido_context, '')) WHERE apelido IS NOT NULL DO UPDATE SET
  name = EXCLUDED.name, title = EXCLUDED.title, portrait = EXCLUDED.portrait,
  public_links = EXCLUDED.public_links, style = EXCLUDED.style,
  style_notes_en = EXCLUDED.style_notes_en, style_notes_pt = EXCLUDED.style_notes_pt,
  birth_year = EXCLUDED.birth_year, birth_year_precision = EXCLUDED.birth_year_precision,
  birth_place = EXCLUDED.birth_place, death_year = EXCLUDED.death_year,
  death_year_precision = EXCLUDED.death_year_precision, death_place = EXCLUDED.death_place,
  bio_en = EXCLUDED.bio_en, bio_pt = EXCLUDED.bio_pt,
  achievements_en = EXCLUDED.achievements_en, achievements_pt = EXCLUDED.achievements_pt,
  notes_en = EXCLUDED.notes_en, notes_pt = EXCLUDED.notes_pt, updated_at = NOW();
