-- ============================================================
-- STATEMENTS FOR: Aberrê de Santo Amaro
-- Generated: 2025-12-15
-- ============================================================
-- Contains all relationships where Aberrê de Santo Amaro is the SUBJECT.
-- NOTE: Uses apelido_context='Santo Amaro' to distinguish from
-- the Salvador Aberrê (Antônio Raimundo Argolo).
-- ============================================================

-- NO ACTIVE STATEMENTS
-- Aberrê de Santo Amaro has no relationships where he is the SUBJECT
-- that reference entities currently in the dataset.

-- ============================================================
-- PENDING RELATIONSHIPS (objects not yet in dataset)
-- ============================================================
-- When Mestre Caiçara is imported, add to his statements file:
-- Caiçara student_of Aberrê (context: Santo Amaro) - training started 1938
--
-- Note: The relationship flows from student to teacher, so the statement
-- belongs in caiçara.sql, NOT here.
