name: Test

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  tests:
    name: Contracts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 9.12.3

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          cache: "pnpm"

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - run: pnpm install --frozen-lockfile

      - run: pnpm lint

      - run: pnpm test
      #   env:
      #     JSON_RPC_PROVIDER: ${{ secrets.JSON_RPC_PROVIDER }}
